---
# Ubuntu Storage Server Role Defaults
# Centralized storage server for camguard recordings and other media files

ubuntu_storage_server_defaults:
  enabled: false

  # Storage configuration
  storage:
    base_path: "/data/orangead"
    camguard_path: "/data/orangead/camguard"
    recordings_path: "/data/orangead/camguard/recordings"
    logs_path: "/data/orangead/camguard/logs"
    temp_path: "/data/orangead/temp"
    backup_path: "/data/orangead/backups"
    
    # Storage limits and management
    max_storage_gb: 400  # Reserve 30GB for system
    cleanup_threshold_percent: 90  # Start cleanup at 90% full
    retention_days: 30  # Keep recordings for 30 days by default
    
    # Directory permissions
    owner: "orangead"
    group: "orangead"
    mode: "0755"

  # Network file sharing
  sharing:
    # SSH/SFTP access
    ssh_enabled: true
    ssh_port: 22
    
    # Optional: NFS sharing for high-performance access
    nfs_enabled: false
    nfs_exports:
      - path: "/data/orangead/camguard"
        clients: "192.168.1.0/24"
        options: "rw,sync,no_subtree_check,no_root_squash"

  # Transfer service configuration
  transfer_service:
    enabled: true
    listen_port: 8022  # Custom SSH port for transfers
    max_concurrent_transfers: 5
    bandwidth_limit_mbps: 50  # Limit to preserve network performance
    
  # Monitoring and health
  monitoring:
    enabled: true
    disk_usage_alert_threshold: 85
    check_interval: 300  # 5 minutes
    log_retention_days: 7

  # Backup configuration
  backup:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM
    retention_days: 7
    compress: true

  # Security settings
  security:
    firewall_enabled: true
    allowed_ips:
      - "100.64.0.0/10"   # Tailscale network (primary)
      - "192.168.1.0/24"  # Local network (backup)
    fail2ban_enabled: true
