---
#SPDX-License-Identifier: MIT-0
# handlers file for roles/macos/tracker

- name: Unload existing launchd service
  ansible.builtin.command: launchctl unload {{ ansible_user_dir }}/Library/LaunchAgents/com.orangead.tracker.plist
  become: false
  failed_when: false
  changed_when: false

- name: Load launchd service
  ansible.builtin.command: launchctl load {{ ansible_user_dir }}/Library/LaunchAgents/com.orangead.tracker.plist
  become: false
  changed_when: false

- name: Start launchd service
  ansible.builtin.command: launchctl start com.orangead.tracker
  become: false
  changed_when: false

- name: Unload existing API launchd service
  ansible.builtin.command: launchctl unload {{ ansible_user_dir }}/Library/LaunchAgents/com.orangead.api.plist
  become: false
  failed_when: false
  changed_when: false

- name: Load API launchd service
  ansible.builtin.command: launchctl load {{ ansible_user_dir }}/Library/LaunchAgents/com.orangead.api.plist
  become: false
  changed_when: false

- name: Start API launchd service
  ansible.builtin.command: launchctl start com.orangead.api
  become: false
  changed_when: false
