---
# Handlers for macos_api role

- name: reload macosapi service
  shell: |
    launchctl unload /Library/LaunchDaemons/com.orangead.macosapi.plist || true
    launchctl load -w /Library/LaunchDaemons/com.orangead.macosapi.plist
  become: true
