---
# Runtime versions
python:
  version: "3.11.11"
node:
  version: "22.11.0"

# Feature toggles
configure:
  tailscale: false
  pyenv: true
  node: true

# Environment-specific features
oa_environment:
  name: "production"
  allow_experimental: false
  allow_server_optimizations: false
  allow_destructive_operations: false
  deploy_alpr_service: false

# System packages
system:
  homebrew:
    packages:
      - go
      - git
      - wget
      - jq
      - btop
      - httpie
      - curl
      - telnet
      - util-linux
      - orbstack
      - lsd

# Tracker configuration
tracker:
  repository_url: "https://github.com/oa-device/oaTracker.git"
  git_version: "main"
  default_yolo_source: 0
  default_model: "yolo12s.pt"
  server_port: 8080

# Dashboard configuration
dashboard:
  url: "http://100.79.103.84"
