---
# Runtime versions
python:
  version: "3.11.11"
node:
  version: "22.11.0"

# Feature toggles
configure:
  tailscale: true
  pyenv: true
  node: true

# System packages
system:
  homebrew:
    packages:
      - go
      - git
      - wget
      - curl

# Tracker configuration
tracker:
  default_yolo_source: 0
  default_model: "yoloe-11s-seg-custom.pt"
  server_port: 8080

# Dashboard configuration
dashboard:
  url: "http://100.79.103.84"
