---
# Runtime versions
python:
  version: "3.11.11"
node:
  version: "22.11.0"

# Feature toggles
configure:
  tailscale: true
  pyenv: true
  node: true

# System packages
system:
  homebrew:
    packages:
      - go
      - git
      - wget
      - curl

# Tracker configuration
tracker:
  default_yolo_source: 0
  cam_id: "macos-{{ inventory_hostname }}"
  default_model: "yolo12s.pt"
  server_port: 8080

# Dashboard configuration
dashboard:
  url: "http://localhost:3000"
