---
# Ubuntu base role defaults

# User configuration
ansible_user: "{{ vault_ubuntu_ansible_user | default('admin') }}"

# System packages to install
ubuntu_base_packages:
  - curl
  - wget
  - git
  - htop
  - vim
  - unzip
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release

# System configuration
ubuntu_timezone: "America/Montreal"
ubuntu_update_cache: true
ubuntu_upgrade_system: false
