---
# macOS Tracker Only Deployment Playbook
# Deploys only the oaTracker component with minimal dependencies
- name: Deploy macOS Tracker Only
  hosts: all
  gather_facts: false
  tags: ["tracker", "components"]
  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Verify target is macOS
      ansible.builtin.fail:
        msg: "This playbook only supports macOS"
      when: ansible_distribution != "MacOSX"

    - name: Display deployment info
      ansible.builtin.debug:
        msg: |
          macOS Tracker Only Deployment:
          - Host: {{ ansible_host }}
          - User: {{ ansible_user }}
          - Target: oaTracker service only

    - name: Environment safety checks
      ansible.builtin.import_tasks: ../tasks/environment_checks.yml
      tags: ["always"]

  roles:
    # Essential dependencies for Tracker
    - role: macos/base
      tags: ["setup", "base"]
      vars:
        minimal_base: true

    - role: macos/python
      tags: ["python", "dependencies"]
      # Python is required for oaTracker

    - role: macos/network
      tags: ["network"]
      vars:
        minimal_network: true

    - role: macos/network/tailscale
      tags: ["tailscale", "network"]
      when: oa_environment.allow_tailscale_changes | default(false)

    - role: macos/tracker
      tags: ["tracker", "main"]
      # Main oaTracker deployment

    - role: macos/security
      tags: ["security"]
      vars:
        security_scope: "tracker_only" # Camera permissions and tracker-specific security

  post_tasks:
    - name: Verify tracker installation
      ansible.builtin.import_tasks: ../tasks/verify.yml
      tags: ["verify"]
      vars:
        verify_scope: "tracker"

    - name: Start tracker service
      ansible.builtin.shell: |
        launchctl load -w "{{ ansible_user_dir }}/Library/LaunchAgents/com.orangead.tracker.plist"
      become: false
      register: tracker_start_result
      failed_when: false

    - name: Display completion message
      ansible.builtin.debug:
        msg: |
          oaTracker Deployment Completed!
          - Service: com.orangead.tracker
          - Port: 8080
          - Status: Check with 'launchctl list | grep orangead'
          - Logs: {{ ansible_user_dir }}/orangead/tracker/logs/
          - Config: {{ ansible_user_dir }}/orangead/tracker/config.yaml
