---
# Network Stack Configuration Playbook
# Configures networking, DNS, and Tailscale across platforms
- name: Configure Network Stack
  hosts: all
  gather_facts: false
  tags: ["network", "tailscale"]
  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Display network deployment info
      ansible.builtin.debug:
        msg: |
          Network Stack Configuration:
          - Platform: {{ ansible_distribution }}
          - Host: {{ ansible_host }}
          - Tailscale: {{ oa_environment.allow_tailscale_changes | default(false) }}

    - name: Environment safety checks
      ansible.builtin.import_tasks: ../tasks/environment_checks.yml
      tags: ["always"]

  tasks:
    - name: Configure macOS network stack
      block:
        - name: Configure macOS network settings
          ansible.builtin.include_role:
            name: macos/network

        - name: Install and configure Tailscale
          ansible.builtin.include_role:
            name: macos/network/tailscale
          when: oa_environment.allow_tailscale_changes | default(false)
      when: ansible_distribution == "MacOSX"
      tags: ["macos"]

    - name: Configure Ubuntu network stack
      block:
        - name: Install and configure Tailscale for Ubuntu
          ansible.builtin.include_role:
            name: ubuntu/network/tailscale
          when: oa_environment.allow_tailscale_changes | default(false)

        - name: Configure Ubuntu network settings
          ansible.builtin.debug:
            msg: "Ubuntu network configuration (beyond Tailscale) will be expanded"
      when: ansible_distribution == "Ubuntu"
      tags: ["ubuntu"]

  post_tasks:
    - name: Verify network configuration
      ansible.builtin.import_tasks: ../tasks/verify.yml
      tags: ["verify"]
      vars:
        verify_scope: "network"

    - name: Test Tailscale connectivity
      block:
        - name: Check Tailscale status
          ansible.builtin.command: tailscale status --json
          register: tailscale_status
          failed_when: false
          become: false

        - name: Display Tailscale status
          ansible.builtin.debug:
            msg: |
              Tailscale Status: {{ 'Connected' if tailscale_status.rc == 0 else 'Not Connected' }}
              {% if tailscale_status.rc == 0 %}
              Details available via: tailscale status
              {% endif %}
      when: oa_environment.allow_tailscale_changes | default(false)

    - name: Display completion message
      ansible.builtin.debug:
        msg: |
          Network Stack Configuration Completed!
          - Platform: {{ ansible_distribution }}
          - Tailscale: {{ 'Configured' if oa_environment.allow_tailscale_changes | default(false) else 'Skipped' }}
          - Network services ready
