---
# Ubuntu Tailscale role defaults

# Tailscale configuration
ubuntu_tailscale_auth_key: "{{ vault_tailscale_auth_key }}"
ubuntu_tailscale_hostname: "{{ inventory_hostname }}"
ubuntu_tailscale_tags:
  - "tag:oa-server"
  - "tag:oa-ubuntu"
ubuntu_tailscale_enable_ssh: true
ubuntu_tailscale_advertise_routes:
  - "192.168.1.0/24"

# Tailscale package repository
ubuntu_tailscale_apt_key_url: "https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg"
ubuntu_tailscale_apt_repo: "deb https://pkgs.tailscale.com/stable/ubuntu jammy main"
