---
# Development Environment Configuration
configure_pyenv: true
pyenv_default_version: "3.10.11"

configure_node: true
node_version: "20.18.0"
node_packages:
  - pm2
  - yarn

configure_xcode: true

# System Configuration
configure_sudoers: true
sudoers_custom_config: |
  # Allow users in admin group to use sudo without password
  %admin ALL=(ALL) NOPASSWD: ALL

# Networking Configuration
configure_tailscale: true

# TODO: Below here are not currently used in current playbook, but are kept for potential future use or reference.

# Homebrew Configuration
homebrew_installed_packages:
  - git
  - wget
  - jq
  - htop

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome

# System Configuration
configure_osx: true
osx_script: "~/.osx --no-restart"

open_ports:
  - 22 # SSH
  - 80 # HTTP
  - 443 # HTTPS
  - 5900 # VNC (Screen Sharing)

configure_automatic_updates: true

# Dock Configuration
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - "App Store"
dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 1
  - name: "Orbstack"
    path: "/Applications/Orbstack.app/"
    pos: 2
