---
# Main Entry Point - Universal OrangeAd Configuration
# This is now a simple wrapper around the universal playbook for backward compatibility
# Recommended usage: Use playbooks/universal.yml directly or the new run-* scripts

- name: OrangeAd Universal Configuration (Legacy Entry Point)
  ansible.builtin.import_playbook: playbooks/universal.yml
  # Note: Variables are passed through from command line via --extra-vars
  # The universal.yml playbook already has sensible defaults for all variables
