---
# Main Entry Point - Universal OrangeAd Infrastructure Automation
# This serves as the primary entry point and routes to the universal playbook
# 
# Usage Examples:
#   ansible-playbook main.yml -i inventory/f1-prod.yml
#   ansible-playbook main.yml -i inventory/f1-prod.yml -t macos-api
#   ansible-playbook main.yml -i inventory/f1-prod.yml -t tracker,security
#
# For advanced usage, you can also call universal.yml directly:
#   ansible-playbook playbooks/universal.yml -i inventory/f1-prod.yml -t macos-api

- name: OrangeAd Universal Infrastructure Automation
  ansible.builtin.import_playbook: playbooks/universal.yml
  # All variables, tags, and extra-vars are automatically passed through to universal.yml
  # The universal.yml playbook handles platform detection, component routing, and validation
