---
# Main Entry Point - Universal OrangeAd Configuration
# This is now a simple wrapper around the universal playbook for backward compatibility
# Recommended usage: Use playbooks/universal.yml directly or the new run-* scripts

- name: OrangeAd Universal Configuration (Legacy Entry Point)
  ansible.builtin.import_playbook: playbooks/universal.yml
  vars:
    # Default to full deployment for backward compatibility
    execution_mode: "{{ execution_mode | default('full') }}"
    # Components can still be specified via extra-vars
    selected_components: "{{ selected_components | default([]) }}"
    # Platform can be forced via extra-vars
    force_platform: "{{ force_platform | default('') }}"
