---
- name: Configure macOS for OrangeAd
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: Ensure system requirements are met
      import_tasks: tasks/pre_checks.yml
      tags: ["always"]

  roles:
    - role: elliotweiser.osx-command-line-tools
      become: yes
      tags: ["cli", "setup"]

    - role: geerlingguy.mac.homebrew
      tags: ["homebrew", "setup"]

    - role: local
      tags: ["setup", "configuration"]

  post_tasks:
    - name: Verify installation
      import_tasks: tasks/verify.yml
      tags: ["verify"]
