---
- name: Configure macOS for OrangeAd
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Gather facts
      setup:

    - name: Debug connection info
      debug:
        msg: |
          Connection Details:
          - Host: {{ ansible_host }}
          - User: {{ ansible_user }}
          - Python: {{ ansible_python.executable }}

    - name: Verify target is macOS
      fail:
        msg: "This playbook only supports macOS"
      when: ansible_distribution != "MacOSX"

    - name: Ensure system requirements are met
      import_tasks: tasks/pre_checks.yml
      tags: ["always"]

  roles:
    - role: elliotweiser.osx-command-line-tools
      become: yes
      tags: ["cli", "setup"]

    - role: geerlingguy.mac.homebrew
      tags: ["homebrew", "setup"]

    - role: local
      tags: ["setup", "configuration"]

  post_tasks:
    - name: Verify installation
      import_tasks: tasks/verify.yml
      tags: ["verify"]

    - name: Display completion message
      debug:
        msg: |
          Installation completed successfully!
          Please restart your terminal to apply all changes.
      tags: ["always"]
