---
- name: Configure macOS for OrangeAd
  hosts: all
  become: yes

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include custom config
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      when: item | length > 0

  roles:
    - role: elliotweiser.osx-command-line-tools
      tags: ["osx", "command-line-tools"]
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ["dock"]

  tasks:
    - name: Configure development environment
      block:
        - import_tasks: roles/main/tasks/pyenv.yml
          when: configure_pyenv | default(true)
          tags: ["python"]

        - import_tasks: roles/main/tasks/node.yml
          when: configure_node | default(true)
          tags: ["node"]

        - import_tasks: roles/main/tasks/xcode.yml
          when: configure_xcode | default(true)
          tags: ["xcode"]

    - name: Configure system and security
      block:
        - name: Configure sudoers
          ansible.builtin.template:
            src: roles/main/templates/sudoers.j2
            dest: /etc/sudoers.d/custom
            validate: "visudo -cf %s"
          when: configure_sudoers | default(true)
          tags: ["sudoers"]

        - import_tasks: roles/main/tasks/tailscale.yml
          when: configure_tailscale | default(true)
          tags: ["tailscale"]

    - name: Configure monitoring
      import_tasks: roles/main/tasks/monitoring.yml
      when: install_monitoring_tools | default(true)
      tags: ["monitoring"]

    - name: Configure macOS specific settings
      import_tasks: roles/main/tasks/osx.yml
      when: configure_osx | default(true)
      tags: ["osx"]

    - name: Run post-provision tasks
      block:
        - name: Run configured post-provision ansible task files
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
      tags: ["post"]
