---
# ALPR service deployment for macOS
# Modular task orchestration for improved maintainability and idempotency

# System setup and prerequisites
- name: System setup and prerequisites
  ansible.builtin.include_tasks: system_setup.yml
  tags: ["alpr", "system", "setup"]

# OrbStack installation and configuration
- name: OrbStack setup and configuration
  ansible.builtin.include_tasks: orbstack_setup.yml
  tags: ["alpr", "orbstack", "docker"]

# Docker setup and image management
- name: Docker setup and image management
  ansible.builtin.include_tasks: docker_setup.yml
  tags: ["alpr", "docker", "images"]

# Service configuration and firewall
- name: Service configuration and firewall setup
  ansible.builtin.include_tasks: service_config.yml
  tags: ["alpr", "config", "firewall"]

# Service management and startup
- name: Service management and startup
  ansible.builtin.include_tasks: service_mgmt.yml
  tags: ["alpr", "service", "management"]

# Verification and health checks
- name: Service verification and health checks
  ansible.builtin.include_tasks: verify.yml
  tags: ["alpr", "verify", "health"]

# Cleanup and optional enhanced features
- name: Cleanup and optional enhancements
  ansible.builtin.include_tasks: cleanup.yml
  tags: ["alpr", "cleanup", "enhanced"]