---
all:
  vars:
    # Environment and project identification
    target_env: "evenko-preprod"
    deployment_environment: "preprod"
    oa_environment:
      name: "evenko-preprod"
      stage: "preprod"


    # Player configuration for Evenko project (dual-screen kiosk mode)
    player:
      enabled: true
      loop_mode: true
      dual_screen: true
      video_selection_strategy: "sequential"
      health_check: true
      restart_on_failure: true
      # Enhanced uptime optimization settings
      health_check_interval: 180 # 3 minutes - reduced frequency to prevent false positive restarts
      restart_attempts: 3
      restart_delay: 15 # Slightly longer delay between restart attempts
      volume: 0.0

      # Kiosk mode settings
      fullscreen: true
      hide_cursor: true
      black_background: true
      disable_screensaver: true
      system_volume_muted: true
      hide_desktop_icons: true

      # Time-based scheduling configuration (Friday 00:00 through Sunday)
      schedule_enabled: true
      schedules:
        # Friday daytime
        - name: "friday_daytime"
          start_time: "00:00"
          end_time: "22:50"
          day_of_week: "friday"
          videos:
            - name: "LASSO_vendredi.mp4"
              display: 1
              enabled: true
              loop: true
              volume: 0.0
            - name: "LASSO_vendredi.mp4"
              display: 2
              enabled: true
              loop: true
              volume: 0.0
        # Friday nighttime (22:50-midnight)
        - name: "friday_nighttime"
          start_time: "22:50"
          end_time: "23:59"
          day_of_week: "friday"
          videos:
            - name: "POUR22h50_LASSO_vendredi.mp4"
              display: 1
              enabled: true
              loop: true
              volume: 0.0
            - name: "POUR22h50_LASSO_vendredi.mp4"
              display: 2
              enabled: true
              loop: true
              volume: 0.0
        # Saturday daytime
        - name: "saturday_daytime"
          start_time: "00:00"
          end_time: "22:50"
          day_of_week: "saturday"
          videos:
            - name: "LASSO_samedi.mp4"
              display: 1
              enabled: true
              loop: true
              volume: 0.0
            - name: "LASSO_samedi.mp4"
              display: 2
              enabled: true
              loop: true
              volume: 0.0
        # Saturday nighttime through end of Sunday
        - name: "saturday_nighttime_extended"
          start_time: "22:50"
          end_time: "23:59"
          day_of_week: "saturday"
          videos:
            - name: "POUR22h50_LASSO_samedi.mp4"
              display: 1
              enabled: true
              loop: true
              volume: 0.0
            - name: "POUR22h50_LASSO_samedi.mp4"
              display: 2
              enabled: true
              loop: true
              volume: 0.0
        # Sunday (continues Saturday nighttime video)
        - name: "sunday_extended"
          start_time: "00:00"
          end_time: "23:59"
          day_of_week: "sunday"
          videos:
            - name: "POUR22h50_LASSO_samedi.mp4"
              display: 1
              enabled: true
              loop: true
              volume: 0.0
            - name: "POUR22h50_LASSO_samedi.mp4"
              display: 2
              enabled: true
              loop: true
              volume: 0.0

      # Smart fallback (last scheduled video based on time)
      videos:
        - name: "POUR22h50_LASSO_samedi.mp4"
          display: 1
          enabled: true
          loop: true
          volume: 0.0
        - name: "POUR22h50_LASSO_samedi.mp4"
          display: 2
          enabled: true
          loop: true
          volume: 0.0

  children:
    # Environment group
    preprod:
      children:
        # Project group
        evenko_project:
          children:
            macos:
              hosts:
                f1-ca-001:
                  ansible_host: 100.103.229.95
                  ansible_user: studio
                  ansible_port: 22
                  ansible_become_password: "{{ vault_sudo_passwords['f1-ca-001'] }}"
                  # Single-screen override for preprod testing (only 1 display available)
                  player_overrides:
                    dual_screen: false
