---
all:
  vars:
    # Environment and project identification
    target_env: "evenko-prod"
    deployment_environment: "production"
    oa_environment:
      name: "evenko-prod"
      stage: "production"

    # Player configuration for Evenko project (dual-screen kiosk mode)
    player:
      enabled: true
      loop_mode: true
      dual_screen: true
      video_selection_strategy: "sequential"
      health_check: true
      restart_on_failure: true
      # Enhanced uptime optimization settings
      health_check_interval: 180 # 3 minutes - reduced frequency to prevent false positive restarts
      restart_attempts: 3
      restart_delay: 15 # Slightly longer delay between restart attempts
      volume: 0.0

      # Kiosk mode settings
      fullscreen: true
      hide_cursor: true
      black_background: true
      disable_screensaver: true
      system_volume_muted: true
      hide_desktop_icons: true

      # Time-based scheduling configuration with day-of-week support
      schedule_enabled: true
      schedules:
        # Friday schedules
        - name: "friday_daytime"
          start_time: "00:00"
          end_time: "22:50"
          day_of_week: "friday"
          videos:
            - name: "LASSO_vendredi.mp4"
              display: 1
              enabled: true
              loop: true
              volume: 0.0
            - name: "LASSO_vendredi.mp4"
              display: 2
              enabled: true
              loop: true
              volume: 0.0
        - name: "friday_nighttime"
          start_time: "22:50"
          end_time: "23:59"
          day_of_week: "friday"
          videos:
            - name: "POUR22h50_LASSO_vendredi.mp4"
              display: 1
              enabled: true
              loop: true
              volume: 0.0
            - name: "POUR22h50_LASSO_vendredi.mp4"
              display: 2
              enabled: true
              loop: true
              volume: 0.0
        # Saturday schedules
        - name: "saturday_daytime"
          start_time: "00:00"
          end_time: "22:50"
          day_of_week: "saturday"
          videos:
            - name: "LASSO_samedi.mp4"
              display: 1
              enabled: true
              loop: true
              volume: 0.0
            - name: "LASSO_samedi.mp4"
              display: 2
              enabled: true
              loop: true
              volume: 0.0
        - name: "saturday_nighttime"
          start_time: "22:50"
          end_time: "23:59"
          day_of_week: "saturday"
          videos:
            - name: "POUR22h50_LASSO_samedi.mp4"
              display: 1
              enabled: true
              loop: true
              volume: 0.0
            - name: "POUR22h50_LASSO_samedi.mp4"
              display: 2
              enabled: true
              loop: true
              volume: 0.0
        # Weekday schedule (Sunday-Thursday): One video all day
        - name: "weekday_allday"
          start_time: "00:00"
          end_time: "23:59"
          day_of_week: "weekday"
          videos:
            - name: "POUR22h50_LASSO_samedi.mp4"
              display: 1
              enabled: true
              loop: true
              volume: 0.0
            - name: "POUR22h50_LASSO_samedi.mp4"
              display: 2
              enabled: true
              loop: true
              volume: 0.0

      # Fallback videos configuration (for backward compatibility)
      videos:
        - name: "LASSO_vendredi.mp4"
          display: 1
          enabled: true
          loop: true
          volume: 0.0
        - name: "LASSO_vendredi.mp4"
          display: 2
          enabled: true
          loop: true
          volume: 0.0

  children:
    # Environment group
    production:
      children:
        # Project group
        evenko_project:
          children:
            macos:
              hosts:
                f1-ca-001:
                  ansible_host: 100.103.229.95
                  ansible_user: studio
                  ansible_port: 22
                  ansible_become_password: "{{ vault_sudo_passwords['f1-ca-001'] }}"
                  # Single-screen override for this device - everything else inherited!
                  player_overrides:
                    dual_screen: false
                f1-ca-002:
                  ansible_host: 100.122.121.83
                  ansible_user: ek003
                  ansible_port: 22
                  ansible_become_password: "{{ vault_sudo_passwords['f1-ca-002'] }}"
                  # Single-screen override for this device - everything else inherited!
                  player_overrides:
                    dual_screen: false
                f1-ca-003:
                  ansible_host: 100.114.173.58
                  ansible_user: ek002
                  ansible_port: 22
                  ansible_become_password: "{{ vault_sudo_passwords['f1-ca-003'] }}"
                  # Single-screen override for this device - everything else inherited!
                  player_overrides:
                    dual_screen: false
                f1-ca-005:
                  ansible_host: 100.120.130.91
                  ansible_user: ek000
                  ansible_port: 22
                  ansible_become_password: "{{ vault_sudo_passwords['f1-ca-005'] }}"
                f1-ca-007:
                  ansible_host: 100.78.224.4
                  ansible_user: admin
                  ansible_port: 22
                  ansible_become_password: "{{ vault_sudo_passwords['f1-ca-007'] }}"
                f1-ca-011:
                  ansible_host: 100.108.127.23
                  ansible_user: admin
                  ansible_port: 22
                  ansible_become_password: "{{ vault_sudo_passwords['f1-ca-011'] }}"
                f1-ca-012:
                  ansible_host: 100.67.135.111
                  ansible_user: admin
                  ansible_port: 22
                  ansible_become_password: "{{ vault_sudo_passwords['f1-ca-012'] }}"
                  # Single-screen override for this device - everything else inherited!
                  player_overrides:
                    dual_screen: false
                f1-ca-016:
                  ansible_host: 100.68.254.108
                  ansible_user: admin
                  ansible_port: 22
                  ansible_become_password: "{{ vault_sudo_passwords['f1-ca-016'] }}"
                  # Single-screen override for this device - everything else inherited!
                  player_overrides:
                    dual_screen: false
