---
# Ubuntu security role handlers

- name: Restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  become: true

- name: Enable ufw
  community.general.ufw:
    state: enabled
  become: true
