---
all:
  vars:
    target_env: alpr-prod
    project_name: alpr
    deployment_environment: production
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_ssh_pipelining: true
    ansible_become_method: sudo

    # Runtime versions
    python:
      version: "3.11.11"
    node:
      version: "22.11.0"

    # Feature toggles
    configure:
      tailscale: false # Production - Tailscale managed separately
      pyenv: true
      node: true

    # Environment-specific features (Production settings)
    oa_environment:
      name: "alpr-prod"
      project: "alpr"
      allow_experimental: false
      allow_server_optimizations: false # Conservative for production
      allow_destructive_operations: false
      # ALPR project components: macos-api, alpr only
      deploy_macos_api: true
      deploy_tracker: false
      deploy_alpr_service: true
      deploy_player: false

    # System packages (minimal for production)
    system:
      homebrew:
        packages:
          - go
          - git
          - wget
          - jq
          - curl
          - lsd
          - docker # Required for ALPR

    # ALPR configuration (Production)
    alpr:
      enabled: true
      docker_image: "platerecognizer/alpr"
      api_port: 8080
      monitor_interval: 10
      camera_source: 0
      detection_threshold: 0.9
      backup_enabled: true
      log_retention_days: 30

  children:
    macos:
      hosts:
        # Placeholder for ALPR production devices
        # alpr-prod-001:
        #   ansible_host: 100.200.200.200
        #   ansible_user: admin
        #   ansible_port: 22
        #   ansible_become_password: "{{ vault_sudo_passwords['alpr-prod-001'] }}"
        #   cam_id: "alpr-cam-001"

    ubuntu_servers:
      hosts:
        # Placeholder for Ubuntu servers if needed
