---
# ML macOS Development Workstation Inventory
# For setting up oaSentinel development and training on macOS machines

all:
  children:
    macos:
      hosts:
        # Add your macOS development machines here
        # Example:
        # kaitran-macbook:
        #   ansible_host: 192.168.1.100
        #   ansible_user: kaitran
        #   ansible_ssh_private_key_file: ~/.ssh/id_rsa
        
        # Localhost example (for self-setup)
        localhost:
          ansible_connection: local
          ansible_user: "{{ lookup('env', 'USER') }}"
          
      vars:
        # Platform identification
        ansible_os_family: Darwin
        
        # ML Workstation Configuration
        development_mode: true
        execute_security_setup: false  # Optional for dev machines
        
        # oaSentinel specific settings
        oasentinel_repo_branch: main
        python_version: "3.11"
        
        # macOS specific ML settings
        install_xcode_tools: true
        macos_dev_env:
          create_desktop_shortcuts: true
          install_iterm2_integration: false
        
        # Apple Silicon optimizations (auto-detected)
        apple_silicon_optimizations:
          enable_mps: true
          optimize_memory: true
        
        # Development tools
        dev_tools:
          enable_jupyter: true
          enable_code_formatting: true
          enable_testing: true
        
        # ML frameworks
        ml_frameworks:
          pytorch: true
          ultralytics: true
          opencv: true
          jupyter: true
          wandb: false
        
        # Training configuration for development
        training_config:
          default_epochs: 50  # Reduced for dev
          default_batch_size: 8  # Conservative for dev
          auto_device_detection: true
        
        # Monitoring and aliases
        create_dev_aliases: true
        enable_health_checks: true