---
all:
  vars:
    target_env: spectra-staging
    project_name: spectra
    deployment_environment: staging
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_ssh_pipelining: true
    ansible_become_method: sudo

    # Runtime versions
    python:
      version: "3.11.11"
    node:
      version: "22.11.0"

    # Feature toggles
    configure:
      tailscale: true
      pyenv: true
      node: true

    # Environment-specific features
    oa_environment:
      name: "spectra-staging"
      project: "spectra"
      allow_experimental: true
      allow_server_optimizations: true
      allow_destructive_operations: true
      # Spectra project components: macos-api, tracker, video-player
      deploy_macos_api: true
      deploy_tracker: true
      deploy_alpr_service: false
      deploy_player: true

    # System packages
    system:
      homebrew:
        packages:
          - go
          - git
          - wget
          - jq
          - btop
          - httpie
          - curl
          - telnet
          - util-linux
          - fish
          - orbstack
          - lsd
          - ffmpeg # Required for video player

    # Tracker configuration
    tracker:
      repository_url: "https://github.com/oa-device/oaTracker.git"
      git_version: "main"
      default_yolo_source: 0
      default_model: "yolo12s.pt"
      server_port: 8080

    # Player configuration for Spectra project
    player:
      enabled: true
      loop_mode: true
      dual_screen: true
      video_selection_strategy: "sequential"
      health_check: true
      restart_on_failure: true
      volume: 0.8

      # Videos configuration - flexible array for Spectra demo content
      videos:
        - name: "spectra-demo-1.mp4"
          display: 1
          enabled: true
          loop: true
          volume: 0.8
        - name: "spectra-demo-2.mp4"
          display: 2
          enabled: true
          loop: true
          volume: 0.8
        - name: "Jazz_video.webm" # Fallback video deployed from role files
          display: 1
          enabled: false
          loop: true
          volume: 0.8

  children:
    macos:
      hosts:
        spectra-ca-001:
          ansible_host: 192.168.1.173
          ansible_user: studio
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['spectra-ca-001'] }}"
          cam_id: "22222222-2222-2222-2222-222222222222"

    ubuntu_servers:
      hosts:
        # Placeholder for Ubuntu servers if needed
