---
all:
  vars:
    target_env: spectra-prod
    project_name: spectra
    deployment_environment: production
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_ssh_pipelining: true
    ansible_become_method: sudo

    # Runtime versions
    python:
      version: "3.11.11"
    node:
      version: "22.11.0"

    # Feature toggles
    configure:
      tailscale: false # Production - Tailscale managed separately
      pyenv: true
      node: true

    # Environment-specific features (Production settings)
    oa_environment:
      name: "spectra-prod"
      project: "spectra"
      allow_experimental: false
      allow_server_optimizations: false # Conservative for production
      allow_destructive_operations: false
      # Spectra project components: macos-api, tracker, video-player
      deploy_macos_api: true
      deploy_tracker: true
      deploy_alpr_service: false
      deploy_player: true

    # System packages (minimal for production)
    system:
      homebrew:
        packages:
          - go
          - git
          - wget
          - jq
          - curl
          - lsd

    # Tracker configuration
    tracker:
      repository_url: "https://github.com/oa-device/oaTracker.git"
      git_version: "main"
      default_yolo_source: 0
      default_model: "yolo12s.pt"
      server_port: 8080

    # Player configuration for Spectra project (Pre-production)
    player:
      enabled: true
      loop_mode: true
      dual_screen: true
      video_selection_strategy: "sequential"
      health_check: true
      restart_on_failure: true
      volume: 0.0

      # Videos configuration - Jazz video for both screens
      videos:
        - name: "Jazz_video.webm"
          display: 1
          enabled: true
          loop: true
          volume: 0.0
        - name: "Jazz_video.webm"
          display: 2
          enabled: true
          loop: true
          volume: 0.0

  children:
    macos:
      hosts:
        spectra-ca-001:
          ansible_host: 100.103.229.95
          ansible_user: studio
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['spectra-ca-001'] }}"
          cam_id: "22222222-2222-2222-2222-222222222222"
