---
all:
  vars:
    # Ansible configuration
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

    # Tailscale configuration
    tailscale_auth_key: "{{ vault_tailscale_auth_key }}"
    tailscale_enable_ssh: true
    tailscale_advertise_routes:
      - "192.168.1.0/24"
    tailscale_tags:
      - "tag:oa-ubuntu"
      - "tag:oa-server"

    # Platform configuration
    platform_type: "ubuntu"

  children:
    ubuntu_servers:
      vars:
        ansible_user: "{{ vault_ubuntu_ansible_user }}"
        ansible_become_password: "{{ vault_ubuntu_sudo_password }}"
      hosts:
        kampus-rig:
          ansible_host: "192.168.1.245"
          ansible_user: "kai"
          ansible_port: 22
          tailscale_hostname: "kampus-rig"
