---
# Component Deployment Task File
# Handles selective deployment of individual components based on platform
- name: Validate component compatibility with platform
  ansible.builtin.set_fact:
    compatible_components: []

- name: Check macOS component compatibility
  ansible.builtin.set_fact:
    compatible_components: "{{ compatible_components + ['macos-api', 'tracker', 'alpr', 'base', 'network', 'security', 'ssh'] }}"
  when: target_platform == "macos"

- name: Check Ubuntu component compatibility
  ansible.builtin.set_fact:
    compatible_components: "{{ compatible_components + ['base', 'network', 'security', 'docker', 'monitoring'] }}"
  when: target_platform == "ubuntu"

- name: Check OrangePi component compatibility
  ansible.builtin.set_fact:
    compatible_components: "{{ compatible_components + ['opi-setup', 'base', 'network', 'optimization'] }}"
  when: target_platform == "orangepi"

- name: Validate selected components
  ansible.builtin.fail:
    msg: |
      Invalid component '{{ item }}' for platform '{{ target_platform }}'.
      Available components: {{ compatible_components | join(', ') }}
  when: item not in compatible_components
  loop: "{{ selected_components }}"

- name: Display deployment plan
  ansible.builtin.debug:
    msg: |
      Component Deployment Plan:
      - Platform: {{ target_platform }}
      - Components: {{ selected_components | join(', ') }}
      - Compatible: {{ compatible_components | join(', ') }}

# macOS Component Deployment
- name: Deploy macOS API component
  ansible.builtin.include_role:
    name: macos/api
  when:
    - target_platform == "macos"
    - "'macos-api' in selected_components"
  tags: ["macos-api", "components"]

- name: Deploy tracker component
  ansible.builtin.include_role:
    name: macos/tracker
  when:
    - target_platform == "macos"
    - "'tracker' in selected_components"
  tags: ["tracker", "components"]

- name: Deploy ALPR service component
  ansible.builtin.include_role:
    name: macos/alpr_service
  when:
    - target_platform == "macos"
    - "'alpr' in selected_components"
  tags: ["alpr", "components"]

- name: Deploy base system component
  when: "'base' in selected_components"
  tags: ["base", "components"]
  block:
    - name: Deploy macOS base
      ansible.builtin.include_role:
        name: macos/base
      when: target_platform == "macos"

    - name: Deploy Ubuntu base
      ansible.builtin.include_role:
        name: ubuntu/base
      when: target_platform == "ubuntu"

    # OrangePi base will be added in Phase 5

- name: Deploy network component
  when: "'network' in selected_components"
  tags: ["network", "components"]
  block:
    - name: Deploy macOS network stack
      ansible.builtin.include_role:
        name: macos/network
      when: target_platform == "macos"

    - name: Deploy macOS Tailscale
      ansible.builtin.include_role:
        name: macos/network/tailscale
      when:
        - target_platform == "macos"
        - oa_environment.allow_tailscale_changes | default(false)

    - name: Deploy Ubuntu network
      ansible.builtin.include_role:
        name: ubuntu/network/tailscale
      when: target_platform == "ubuntu"

- name: Deploy security component
  when: "'security' in selected_components"
  tags: ["security", "components"]
  block:
    - name: Deploy macOS security
      ansible.builtin.include_role:
        name: macos/security
      when: target_platform == "macos"

    - name: Deploy Ubuntu security
      ansible.builtin.include_role:
        name: ubuntu/security
      when: target_platform == "ubuntu"

- name: Deploy SSH component
  ansible.builtin.include_role:
    name: macos/ssh
  when:
    - target_platform == "macos"
    - "'ssh' in selected_components"
  tags: ["ssh", "components"]

# Ubuntu-specific components
- name: Deploy Docker component
  ansible.builtin.include_role:
    name: ubuntu/docker
  when:
    - target_platform == "ubuntu"
    - "'docker' in selected_components"
  tags: ["docker", "components"]

# OrangePi-specific components (to be implemented in Phase 5)
- name: Deploy OPI setup component
  ansible.builtin.debug:
    msg: "OrangePi components will be implemented in Phase 5"
  when:
    - target_platform == "orangepi"
    - "'opi-setup' in selected_components"
  tags: ["opi-setup", "components"]

- name: Component deployment summary
  ansible.builtin.debug:
    msg: |
      Component Deployment Completed:
      - Platform: {{ target_platform }}
      - Components: {{ selected_components | join(', ') }}
      - Host: {{ inventory_hostname }}
