---
- name: Configure Node.js and nvm
  block:
    - name: Install Node.js
      homebrew:
        name: node
        state: present

    - name: Install nvm
      homebrew:
        name: nvm
        state: present

    - name: Install specific Node.js version
      shell: . /usr/local/opt/nvm/nvm.sh && nvm install {{ node_version }} && nvm alias default {{ node_version }}
      args:
        executable: /bin/bash
      when: configure_node | bool
