---
- name: Gather system facts
  setup:
    gather_subset:
      - hardware
      - network
      - virtual
  tags: ["always"]

- name: Set system facts
  set_fact:
    memory_gb: "{{ ansible_memtotal_mb | int // 1024 }}"
    homebrew_prefix: "{{ (ansible_architecture == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
    is_apple_silicon: "{{ ansible_architecture == 'arm64' }}"
    has_xcode: "{{ xcode_check.stat.exists | default(false) }}"
  tags: ["always"]

- name: Verify system requirements
  assert:
    that:
      - memory_gb | int >= 8
      - ansible_distribution == "MacOSX"
    fail_msg: |
      System requirements not met:
      - Minimum 8GB RAM required (found: {{ memory_gb }}GB)
      - Must be running macOS (found: {{ ansible_distribution }})
    success_msg: "System requirements verified successfully"
  tags: ["always"]

- name: Debug system information
  debug:
    msg: |
      System Information:
      - OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
      - Architecture: {{ ansible_architecture }}
      - Memory: {{ memory_gb }}GB
      - Homebrew Prefix: {{ homebrew_prefix }}
      - Has Xcode CLI: {{ has_xcode }}
  tags: ["always", "debug"]
