---
- name: Gather system facts
  setup:
    gather_subset:
      - hardware
      - network
      - virtual
  tags: ["always"]

- name: Set system facts
  set_fact:
    is_apple_silicon: "{{ ansible_architecture == 'arm64' }}"
    has_xcode: "{{ lookup('pipe', 'xcode-select -p 2>/dev/null || echo false') != 'false' }}"
    memory_gb: "{{ ansible_memtotal_mb / 1024 }}"
    homebrew_prefix: "{{ (ansible_architecture == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
  tags: ["always"]

- name: Verify system requirements
  assert:
    that:
      - ansible_distribution == "MacOSX"
      - ansible_distribution_version is version('11.0', '>=')
      - memory_gb >= 8
    fail_msg: |
      System does not meet minimum requirements:
      - Must be macOS 11.0 or higher
      - Must have at least 8GB RAM
      - Current system: {{ ansible_distribution }} {{ ansible_distribution_version }}
      - Current RAM: {{ memory_gb }}GB
  tags: ["always"]

- name: Debug system information
  debug:
    msg: |
      System Information:
      - OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
      - Architecture: {{ ansible_architecture }}
      - Memory: {{ memory_gb }}GB
      - Homebrew Prefix: {{ homebrew_prefix }}
      - Has Xcode CLI: {{ has_xcode }}
  tags: ["always", "debug"]
