---
- name: Check SSH connectivity
  wait_for_connection:
    timeout: 10
  tags: ["always"]

- name: Gather target OS information
  setup:
    filter: 
      - ansible_distribution
      - ansible_distribution_version
  tags: ["always"]

- name: Verify target is macOS
  fail:
    msg: "This playbook only supports macOS systems"
  when: ansible_distribution != "MacOSX"
  tags: ["always"]

- name: Check sudo access
  command: sudo -n true
  register: sudo_check
  failed_when: false
  changed_when: false
  tags: ["always"]

- name: Display pre-check results
  debug:
    msg: |
      Pre-check Results:
      =================
      OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
      Sudo Access: {{ 'Available' if sudo_check.rc == 0 else 'Requires Password' }}
  tags: ["always"]
