---
- name: Verify installations
  block:
    - name: Verify Python environment
      block:
        - name: Check pyenv installation
          stat:
            path: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv"
          register: pyenv_binary

        - name: Get Python version
          shell: |
            source {{ shell_profile }}
            pyenv version
          register: python_version
          changed_when: false
          failed_when: false
          when: pyenv_binary.stat.exists
      when: configure.pyenv | bool
      tags: ["verify", "python"]

    - name: Verify Node.js environment
      block:
        - name: Check NVM installation
          stat:
            path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
          register: nvm_script

        - name: Get Node.js version
          shell: |
            source {{ shell_profile }}
            node --version
          register: node_version
          changed_when: false
          failed_when: false
          when: nvm_script.stat.exists
      when: configure.node | bool
      tags: ["verify", "node"]

    - name: Verify Tailscale
      block:
        - name: Check if Tailscale binary exists
          stat:
            path: /usr/local/bin/tailscale
          register: tailscale_binary_exists

        - name: Check Tailscale status
          command: /usr/local/bin/tailscale status
          register: tailscale_status
          changed_when: false
          failed_when: false
          when: tailscale_binary_exists.stat.exists

        - name: Get Tailscale version
          command: /usr/local/bin/tailscale version
          register: tailscale_version
          changed_when: false
          failed_when: false
          when: tailscale_binary_exists.stat.exists
      when: configure.tailscale | bool
      tags: ["verify", "tailscale"]

    - name: Display verification results
      debug:
        msg: |
          Verification Results:
          {% if configure.pyenv %}
          Python: {{ python_version.stdout if python_version.rc == 0 else 'Not installed' }}
          {% endif %}
          {% if configure.node %}
          Node.js: {{ node_version.stdout if node_version.rc == 0 else 'Not installed' }}
          {% endif %}
          {% if configure.tailscale %}
          Tailscale: {% if not tailscale_binary_exists.stat.exists %}Not installed{% elif tailscale_status.rc == 0 %}Connected ({{ tailscale_version.stdout | default('unknown version') }}){% else %}Installed but not connected{% endif %}
          {% endif %}
      tags: ["verify"]

  rescue:
    - name: Handle verification failures
      debug:
        msg: "Verification failed. Please check the installation logs for details."
