---
- name: Configure Xcode
  block:
    - name: Install Xcode Command Line Tools
      command: xcode-select --install
      ignore_errors: true
      when: configure_xcode | bool

    - name: Accept Xcode license
      command: xcodebuild -license accept
      become: true
      when: configure_xcode | bool
