---
# Common service manager tasks for cross-platform service management

- name: Detect service manager
  block:
    - name: Set service manager facts
      ansible.builtin.set_fact:
        platform_os: "{{ ansible_distribution }}"
        platform_family: "{{ ansible_os_family }}"
        service_manager_type: "{{ 'launchd' if ansible_os_family == 'Darwin' else 'systemd' }}"
        service_commands_map: "{{ service_commands[ansible_distribution] }}"

    - name: Display service manager detection
      ansible.builtin.debug:
        msg: |
          Service Manager Detection:
          - OS: {{ platform_os }}
          - Family: {{ platform_family }}
          - Service Manager: {{ service_manager_type }}

- name: Manage common services
  ansible.builtin.include_tasks: "manage_{{ service_manager_type }}.yml"
  when: common_services is defined

- name: Create service configurations
  ansible.builtin.include_tasks: create_service_config.yml
  loop: "{{ common_service_configs | default([]) }}"
  loop_control:
    loop_var: service_config

- name: Enhanced service management
  block:
    - name: Install service monitoring tools (macOS)
      community.general.homebrew:
        name:
          - pstree
          - htop
        state: present
        update_homebrew: false
      when:
        - service_manager_type == 'launchd'
        - ansible_os_family == 'Darwin'
      failed_when: false

    - name: Install service monitoring tools (Linux)
      ansible.builtin.package:
        name:
          - psmisc
          - htop
          - systemd-cron
        state: present
      when:
        - service_manager_type == 'systemd'
        - ansible_os_family != 'Darwin'
      become: true
      failed_when: false

    - name: Enhanced service monitoring setup
      ansible.builtin.debug:
        msg: |
          Enhanced Service Management Features:
          - Service monitoring tools installed
          - Cross-platform service lifecycle management
          - Advanced logging and debugging capabilities

    - name: Create service monitoring script
      ansible.builtin.template:
        src: monitor_services.sh.j2
        dest: "{{ ansible_user_dir }}/bin/monitor_services.sh"
        mode: "0755"
      when: create_monitoring_script | default(false)

  rescue:
    - name: Enhanced service setup failed
      ansible.builtin.debug:
        msg: "Enhanced service features encountered issues, but core functionality remains available"

- name: Verify service states
  ansible.builtin.include_tasks: verify_services.yml
  when:
    - verify_services | default(true)
    - common_services is defined
