---
# Pre-flight checks for macOS systems

- name: Verify Homebrew is installed
  ansible.builtin.command: which brew
  register: brew_check
  changed_when: false
  failed_when: false

- name: Install Homebrew if missing
  ansible.builtin.shell: |
    set -o pipefail
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: brew_check.rc != 0
  become: true
  become_user: "{{ ansible_user }}"
  changed_when: true

- name: Check Python installation
  ansible.builtin.command: which python3
  register: python_check
  changed_when: false
  failed_when: false

- name: Install Python via Homebrew if missing
  community.general.homebrew:
    name: python@3.12
    state: present
  when: python_check.rc != 0
  changed_when: true

- name: Check Ansible installation
  ansible.builtin.command: which ansible
  register: ansible_check
  changed_when: false
  failed_when: false

- name: Install Ansible via pip if missing
  ansible.builtin.pip:
    name: ansible
    state: present
  when: ansible_check.rc != 0
  changed_when: true

- name: Verify required directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ ansible_user_dir }}/orangead"
    - "{{ ansible_user_dir }}/orangead/macos-api"
    - "{{ ansible_user_dir }}/orangead/tracker"
    - "{{ ansible_user_dir }}/orangead/player"
  changed_when: false
