---
- name: Configure DNS Settings
  block:
    - name: Get current DNS servers
      command: networksetup -getdnsservers Wi-Fi
      register: current_dns
      changed_when: false

    - name: Set fact for current DNS servers
      set_fact:
        current_dns_servers: "{{ current_dns.stdout.split('\n') | select('ne', 'There aren't any DNS Servers set on Wi-Fi.') | list }}"
      when: current_dns.rc == 0

    - name: Get DHCP-provided DNS servers
      command: ipconfig getpacket en0
      register: dhcp_info
      changed_when: false

    - name: Extract DHCP DNS servers
      set_fact:
        dhcp_dns_servers: "{{ dhcp_info.stdout | regex_findall('domain_name_server[^\\n]*\\n\\s+([^\\n]*)') | first | split(' ') }}"
      when: dhcp_info.rc == 0

    - name: Configure DNS servers
      command: >
        networksetup -setdnsservers Wi-Fi 
        {{ ((current_dns_servers | default([])) + (dhcp_dns_servers | default([])) + ['100.100.100.100']) | unique | join(' ') }}
      when: 
        - configure_tailscale | bool
        - dhcp_info.rc == 0
      register: dns_result
      changed_when: dns_result.rc == 0

    - name: Verify DNS configuration
      command: scutil --dns
      register: dns_verify
      changed_when: false
      failed_when: false
  become: true
