---
- name: Reset DNS Settings
  block:
    - name: Get DHCP-provided DNS servers
      command: ipconfig getpacket en0
      register: dhcp_info
      changed_when: false

    - name: Extract DHCP DNS servers
      set_fact:
        dhcp_dns_servers: "{{ dhcp_info.stdout | regex_findall('domain_name_server[^\\n]*\\n\\s+([^\\n]*)') | first | split(' ') }}"
      when: dhcp_info.rc == 0

    - name: Restore original DNS servers
      command: >
        networksetup -setdnsservers Wi-Fi {{ dhcp_dns_servers | join(' ') }}
      when: dhcp_dns_servers is defined
  become: true
