---
# Install and configure Node.js
- name: Configure Node.js
  block:
    # Check if NVM is installed
    - name: Check if NVM is installed
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      register: nvm_install

    # Install NVM if not already installed
    - name: Install NVM
      ansible.builtin.shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      when: not nvm_install.stat.exists

    # Add NVM to shell profile
    - name: Add NVM to shell profile
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.bash_profile"
        block: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
        marker: "# {mark} ANSIBLE MANAGED BLOCK - NVM"
        create: yes

    # Install Node.js using NVM
    - name: Install Node.js with NVM
      ansible.builtin.shell: |
        source {{ ansible_env.HOME }}/.nvm/nvm.sh
        nvm install {{ node_version }}
        nvm alias default {{ node_version }}
      args:
        executable: /bin/bash
      register: node_install
      changed_when: "'is already installed.' not in node_install.stdout"

    # Install global npm packages
    - name: Install global npm packages
      ansible.builtin.npm:
        name: "{{ item }}"
        global: yes
        state: latest
      loop:
        - pm2
        - yarn
      environment:
        PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_version }}/bin:{{ ansible_env.PATH }}"

  when: configure_node | bool
  # This entire block will only run if configure_node is set to true in default.config.yml
