---
# Install and configure pyenv and Python
- name: Configure pyenv and Python
  block:
    # Check if pyenv is already installed
    - name: Check if pyenv is installed
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.pyenv"
      register: pyenv_install

    # Install pyenv if not already installed
    - name: Install pyenv
      ansible.builtin.git:
        repo: https://github.com/pyenv/pyenv.git
        dest: "{{ ansible_env.HOME }}/.pyenv"
        version: master
        update: yes
      when: not pyenv_install.stat.exists

    # Add pyenv to PATH
    - name: Add pyenv to PATH
      ansible.builtin.lineinfile:
        dest: "{{ ansible_env.HOME }}/.bash_profile"
        line: 'export PATH="$HOME/.pyenv/bin:$PATH"'
        create: yes
      
    # Initialize pyenv
    - name: Initialize pyenv
      ansible.builtin.lineinfile:
        dest: "{{ ansible_env.HOME }}/.bash_profile"
        line: 'eval "$(pyenv init -)"'
        create: yes

    # Install specific Python version
    - name: Check if Python version is installed
      ansible.builtin.shell: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        pyenv versions | grep {{ pyenv_default_version }}
      args:
        executable: /bin/bash
      register: python_version_check
      changed_when: false
      failed_when: false

    - name: Install Python version
      ansible.builtin.shell: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        pyenv install {{ pyenv_default_version }} -s
        pyenv global {{ pyenv_default_version }}
      args:
        executable: /bin/bash
      register: pyenv_install_result
      when: python_version_check.rc != 0 or python_version_check.stdout == ""

    # Rehash pyenv only when new version is installed
    - name: Rehash pyenv
      ansible.builtin.shell: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        pyenv rehash
      args:
        executable: /bin/bash
      when: pyenv_install_result.changed | default(false)

  when: configure_pyenv | bool
  # This entire block will only run if configure_pyenv is set to true in default.config.yml
