---
- name: Configure Tailscale
  block:
    - name: Check if Tailscale is installed
      command: "{{ homebrew_prefix }}/bin/brew list tailscale"
      register: tailscale_check
      changed_when: false
      failed_when: false

    - name: Install Tailscale via Homebrew
      command: "{{ homebrew_prefix }}/bin/brew install tailscale"
      when: tailscale_check.rc != 0

    - name: Start Tailscale service
      command: "{{ homebrew_prefix }}/bin/brew services start tailscale"
      register: tailscale_service
      changed_when: tailscale_service.rc == 0

    - name: Wait for Tailscale daemon to be ready
      wait_for:
        timeout: 10

    - name: Configure DNS settings
      include_tasks: dns.yml
      when: dns_config.enable_magic_dns | default(true)

  environment:
    PATH: "{{ homebrew_prefix }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"
