---
- name: Configure Tailscale
  block:
    - name: Check if Tailscale is installed
      command: "{{ homebrew_prefix }}/bin/brew list tailscale"
      register: tailscale_check
      changed_when: false
      failed_when: false

    - name: Install Tailscale via Homebrew
      command: "{{ homebrew_prefix }}/bin/brew install tailscale"
      when: tailscale_check.rc != 0

    # Start Tailscale service with proper privileges
    - name: Start Tailscale service
      block:
        # First try to start as user
        - name: Start Tailscale service as user
          command: "{{ homebrew_prefix }}/bin/brew services start tailscale"
          register: tailscale_service
          changed_when: tailscale_service.rc == 0
          failed_when: false

        # If user-level start fails, try as root with proper setup
        - name: Start Tailscale service as root
          block:
            - name: Stop existing service if running
              command: "{{ homebrew_prefix }}/bin/brew services stop tailscale"
              become: false
              failed_when: false

            - name: Create system service directory
              become: true
              file:
                path: /Library/LaunchDaemons
                state: directory
                mode: "0755"

            - name: Get Tailscale version
              command: "{{ homebrew_prefix }}/bin/brew list tailscale --versions"
              register: tailscale_version
              changed_when: false

            - name: Extract Tailscale version
              set_fact:
                tailscale_current_version: "{{ tailscale_version.stdout.split(' ')[1] }}"

            - name: Copy service file to system location
              become: true
              command: "cp {{ homebrew_prefix }}/Cellar/tailscale/{{ tailscale_current_version }}/homebrew.mxcl.tailscale.plist /Library/LaunchDaemons/"

            - name: Load service with launchctl
              become: true
              command: launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.tailscale.plist
          when: tailscale_service.rc != 0

    - name: Wait for Tailscale daemon to be ready
      wait_for:
        timeout: 10

    - name: Configure DNS settings
      include_tasks: dns.yml
      when: dns_config.enable_magic_dns | default(true)

    - name: Ensure Tailscale is running
      block:
        # First stop any existing services
        - name: Stop existing services
          command: "{{ homebrew_prefix }}/bin/brew services stop tailscale"
          failed_when: false

        # Remove any existing launch daemon
        - name: Remove existing launch daemon
          file:
            path: /Library/LaunchDaemons/homebrew.mxcl.tailscale.plist
            state: absent
          become: true
          failed_when: false

        # Start as root service (recommended for Tailscale)
        - name: Start Tailscale as root service
          block:
            - name: Create system service directory
              file:
                path: /Library/LaunchDaemons
                state: directory
                mode: "0755"
              become: true

            - name: Copy service file to system location
              command: "cp {{ homebrew_prefix }}/opt/tailscale/homebrew.mxcl.tailscale.plist /Library/LaunchDaemons/"
              become: true

            - name: Load service with launchctl
              command: launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.tailscale.plist
              become: true

        - name: Wait for Tailscale daemon to be ready
          wait_for:
            timeout: 15

  environment:
    PATH: "{{ homebrew_prefix }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"
