---
- name: Check if Tailscale binaries are already installed
  stat:
    path: "{{ ansible_env.HOME }}/go/bin/tailscale"
  register: tailscale_installed

- name: Ensure Go is installed
  homebrew:
    name: go
    state: present
  when: not tailscale_installed.stat.exists

- name: Compile Tailscale from source
  shell: |
    go install tailscale.com/cmd/tailscale{,d}@main
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
    PATH: "{{ ansible_env.PATH }}:/opt/homebrew/bin:/usr/local/bin"
  when: not tailscale_installed.stat.exists

- name: Ensure /usr/local/bin directory exists
  file:
    path: /usr/local/bin
    state: directory
    mode: "0755"
    owner: root
    group: wheel
  become: true

- name: Install and start tailscaled service
  block:
    - name: Install tailscaled as a system daemon
      command: "{{ ansible_env.HOME }}/go/bin/tailscaled install-system-daemon"
      register: install_daemon
      changed_when: "'already installed' not in install_daemon.stderr"
      failed_when:
        - install_daemon.rc != 0
        - "'already installed' not in install_daemon.stderr"
  become: true

- name: Configure Tailscale network
  block:
    - name: Check Tailscale daemon status
      command: launchctl list com.tailscale.tailscaled
      register: tailscale_daemon_status
      changed_when: false
      failed_when: false

    - name: Check current DNS configuration
      command: networksetup -getdnsservers Wi-Fi
      register: current_dns
      changed_when: false
      failed_when: false

    - name: Check Tailscale login status
      command: /usr/local/bin/tailscale status
      register: tailscale_login_status
      changed_when: false
      failed_when: false

    - name: Set DNS server for MagicDNS
      command: networksetup -setdnsservers Wi-Fi 100.100.100.100
      when:
        - tailscale_daemon_status.rc == 0
        - "'100.100.100.100' not in current_dns.stdout"
  become: true
