---
- name: Configure Tailscale
  block:
    - name: Ensure Homebrew path is in PATH
      set_fact:
        brew_path: "{{ '/opt/homebrew/bin:/usr/local/bin:' + ansible_env.PATH }}"

    - name: Check if Tailscale is installed
      command: "{{ homebrew_prefix }}/bin/brew list tailscale"
      register: tailscale_check
      changed_when: false
      failed_when: false
      environment:
        PATH: "{{ brew_path }}"

    - name: Install Tailscale via Homebrew
      command: "{{ homebrew_prefix }}/bin/brew install tailscale"
      when: tailscale_check.rc != 0
      environment:
        PATH: "{{ brew_path }}"

    - name: Start Tailscale service
      command: "{{ homebrew_prefix }}/bin/brew services start tailscale"
      register: tailscale_service
      changed_when: tailscale_service.rc == 0
      environment:
        PATH: "{{ brew_path }}"

    - name: Wait for Tailscale daemon to be ready
      wait_for:
        timeout: 10

    - name: Check Tailscale daemon status
      command: launchctl list com.tailscale.tailscaled
      register: tailscale_daemon_status
      changed_when: false
      failed_when: false

    # Only configure DNS after Tailscale is properly running
    - name: Configure DNS settings
      include_tasks: dns.yml
      when: tailscale_daemon_status.rc == 0
  become: false
