---
# Ubuntu server optimization role defaults

# System optimization
ubuntu_system_optimization:
  enabled: true

  # Kernel parameters
  kernel_params:
    # Network optimization
    net.core.rmem_max: 134217728
    net.core.wmem_max: 134217728
    net.core.rmem_default: 65536
    net.core.wmem_default: 65536
    net.core.netdev_max_backlog: 5000
    net.ipv4.tcp_rmem: "4096 65536 134217728"
    net.ipv4.tcp_wmem: "4096 65536 134217728"
    net.ipv4.tcp_congestion_control: "bbr"

    # Memory management
    vm.swappiness: 10
    vm.dirty_ratio: 15
    vm.dirty_background_ratio: 5
    vm.vfs_cache_pressure: 50

    # File system
    fs.file-max: 1000000
    fs.nr_open: 1000000

    # Security
    kernel.dmesg_restrict: 1
    kernel.kptr_restrict: 2
    net.ipv4.conf.all.log_martians: 1
    net.ipv4.conf.default.log_martians: 1

  # System limits
  limits:
    - domain: "{{ ansible_user }}"
      type: soft
      item: nofile
      value: 65536
    - domain: "{{ ansible_user }}"
      type: hard
      item: nofile
      value: 65536
    - domain: root
      type: soft
      item: nofile
      value: 65536
    - domain: root
      type: hard
      item: nofile
      value: 65536

# Service optimization
ubuntu_service_optimization:
  enabled: true

  # Services to disable (not needed on server)
  services_to_disable:
    - bluetooth
    - cups
    - cups-browsed
    - avahi-daemon
    - whoopsie
    - kerneloops
    - accounts-daemon
    - fwupd
    - snapd.seeded.service
    - snapd.socket
    - snapd.service

  # Services to enable
  services_to_enable:
    - ssh
    - systemd-timesyncd
    - ufw
    - cron
    - rsyslog

# Boot optimization
ubuntu_boot_optimization:
  enabled: true
  grub_timeout: 2

  # GRUB kernel parameters for optimization
  grub_cmdline_params:
    - "quiet"
    - "splash"
    - "nomodeset"
    - "elevator=deadline"
    - "intel_idle.max_cstate=1"
    - "processor.max_cstate=1"

# Package optimization
ubuntu_package_optimization:
  enabled: true

  # Packages to remove (bloatware)
  packages_to_remove:
    - snapd
    - ubuntu-web-launchers
    - ubuntu-report
    - popularity-contest
    - apport
    - whoopsie
    - kerneloops

  # Essential packages to ensure are installed
  essential_packages:
    - curl
    - wget
    - htop
    - iotop
    - tree
    - unzip
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - gnupg
    - lsb-release

# Storage optimization
ubuntu_storage_optimization:
  enabled: true

  # Automatic filesystem trimming
  enable_fstrim: true
  fstrim_schedule: "weekly"

  # Temporary directory cleanup
  tmp_cleanup:
    enabled: true
    max_age_days: 7

  # Log rotation optimization
  log_rotation:
    enabled: true
    max_size: "100M"
    rotate_count: 4
    compress: true

# Network optimization
ubuntu_network_optimization:
  enabled: true

  # DNS optimization
  dns_servers:
    - "1.1.1.1"
    - "8.8.8.8"
    - "8.8.4.4"

  # Network interface optimization
  network_interface_optimization: true

# Security hardening
ubuntu_security_hardening:
  enabled: true

  # SSH hardening (in addition to security role)
  ssh_hardening:
    max_auth_tries: 3
    login_grace_time: 30
    max_sessions: 4

  # Automatic security updates
  unattended_upgrades:
    enabled: true
    automatic_reboot: false
    automatic_reboot_time: "02:00"

# Performance monitoring
ubuntu_performance_monitoring:
  enabled: true

  # System resource monitoring
  resource_monitoring: true

  # Performance baseline collection
  collect_baseline: true

# Ethernet optimization
ubuntu_ethernet_optimization:
  enabled: true

  # Hardware detection
  detect_realtek: true
  realtek_chip_patterns:
    - "RTL8111"
    - "RTL8168"
    - "RTL8211"
    - "RTL8411"

  # Driver configuration
  driver_options:
    r8169:
      use_dac: 1
      eee_enable: 0 # Disable Energy Efficient Ethernet
      debug: 0

  # Power management
  power_management:
    disable_wol: true
    disable_interface_pm: true
    create_service: true

  # Speed optimization
  speed_optimization:
    enabled: true
    force_autoneg: true
    expected_speed: "1000Mb/s"
    fallback_speed: "100Mb/s"
    verify_after_config: true

  # Network monitoring
  monitoring:
    enabled: true
    interval_minutes: 2
    log_retention_days: 7
    monitor_tailscale: true
    monitor_internet: true
    log_path: "/home/{{ ansible_user }}/orangead/network-monitor"

  # Troubleshooting
  diagnostics:
    create_scripts: true
    include_ethtool_stats: true
    include_driver_info: true
