---
# Encrypt this file with: ansible-vault encrypt group_vars/all/vault.yml

# Tailscale configuration
vault_tailscale_auth_key: "tskey-auth-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
vault_tailscale_api_key: "tskey-api-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
vault_tailscale_tailnet: "orangead.ca"
vault_tailscale_tags_macos: "tag:oa-macos,tag:oa-tracker"

# SSH keys - REQUIRED for all deployments
vault_ssh_private_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  # Your private key here
  -----END OPENSSH PRIVATE KEY-----
vault_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2E... user@example.com"
# Host-specific sudo passwords - REQUIRED
vault_sudo_passwords:
  kampus-rig: "machine-password"
  kai-vm-001: "machine-password"
  kai-vm-002: "machine-password"
  # Add more hosts as needed
  # hostname: "password"

# Default sudo password (fallback if host-specific not found)
vault_default_sudo_password: "default_password"

# Ubuntu server configuration (OPTIONAL - only for new Ubuntu servers)
vault_ubuntu_ansible_user: "admin"
vault_ubuntu_sudo_password: "ubuntu-server-sudo-password"

# Tracker secrets (for macOS tracking service)
vault_tracker_access_key: "tracker-access-key"
vault_tracker_secret_key: "tracker-secret-key"

# ALPR service secrets (optional)
vault_alpr_token: "platerecognizer-api-token"
vault_alpr_license_key: "platerecognizer-license-key"
