---
# Encrypt this file with: ansible-vault encrypt group_vars/all/vault.yml

# Tailscale configuration
vault_tailscale_auth_key: "tskey-auth-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
vault_tailscale_api_key: "tskey-api-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
vault_tailscale_tailnet: "orangead.ca"
vault_tailscale_tags_macos: "tag:oa-macos,tag:oa-tracker"

# SSH keys
vault_ssh_private_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  # Your private key here
  -----END OPENSSH PRIVATE KEY-----
vault_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2E... user@example.com"

# Sudo passwords for each host
vault_sudo_passwords:
  b2: "password_for_b2"
  b3: "password_for_b3"

# Default sudo password (fallback if host-specific not found)
vault_default_sudo_password: "default_password"
