---
# Encrypt this file with: ansible-vault encrypt group_vars/all/vault.yml

# Tailscale configuration
vault_tailscale_auth_key: "tskey-auth-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
vault_tailscale_api_key: "tskey-api-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
vault_tailscale_tailnet: "orangead.ca"
vault_tailscale_tags_macos: "tag:oa-macos,tag:oa-tracker"

# SSH keys
vault_ssh_private_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  # Your private key here
  -----END OPENSSH PRIVATE KEY-----
vault_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2E... user@example.com"
# Sudo passwords for each host
vault_sudo_passwords:
  f1-ca-001: "host-specific-password"
  f1-ca-002: "host-specific-password"
  f1-ca-003: "host-specific-password"
  f1-ca-004: "host-specific-password"
  f1-ca-005: "host-specific-password"
  f1-ca-006: "host-specific-password"
  f1-ca-007: "host-specific-password"
  f1-ca-008: "host-specific-password"
  f1-ca-009: "host-specific-password"
  f1-ca-010: "host-specific-password"
  f1-ca-011: "host-specific-password"
  f1-ca-012: "host-specific-password"
  f1-ca-013: "host-specific-password"
  f1-ca-014: "host-specific-password"
  f1-ca-015: "host-specific-password"

# Default sudo password (fallback if host-specific not found)
vault_default_sudo_password: "default_password"
