# Encrypt this file with: ansible-vault encrypt group_vars/all/vault.yml

# Tailscale configuration
vault_tailscale_auth_key: "tskey-auth-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
vault_tailscale_api_key: "tskey-api-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
vault_tailscale_tailnet: "example.tailscale.com"

# macOS API configuration
vault_macos_api_key: "your_strong_randomly_generated_api_key_here"

# SSH keys
vault_ssh_private_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  # Your private key here
  -----END OPENSSH PRIVATE KEY-----

vault_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2E... user@example.com"
