---
# OrangePi base role defaults

# System identification
orangepi_model: "OrangePi 5B"
orangepi_board_id: "orangepi-5b"

# Base packages for OrangePi
orangepi_base_packages:
  - build-essential
  - git
  - curl
  - wget
  - htop
  - iotop
  - tree
  - unzip
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - python3
  - python3-pip
  - python3-venv
  - python3-dev
  - pkg-config
  - cmake
  - libjpeg-dev
  - libpng-dev
  - libtiff-dev
  - libavcodec-dev
  - libavformat-dev
  - libswscale-dev
  - libv4l-dev
  - libxvidcore-dev
  - libx264-dev
  - libgtk-3-dev
  - libatlas-base-dev
  - gfortran
  - ffmpeg
  - v4l-utils

# GPIO and hardware access
gpio_configuration:
  enabled: true
  gpio_group: "gpio"
  i2c_group: "i2c"
  spi_group: "spi"

  # Hardware modules to enable
  kernel_modules:
    - i2c-dev
    - spi-dev
    - gpio-dev
    - v4l2loopback

# Power management
power_management:
  enabled: true

  # CPU governor for embedded performance
  cpu_governor: "ondemand" # ondemand, performance, powersave

  # Thermal management
  thermal_management:
    enabled: true
    critical_temp: 85 # Celsius
    warning_temp: 75 # Celsius

  # Power saving features
  power_saving:
    usb_autosuspend: true
    wifi_power_save: false # Keep WiFi active for remote management
    hdmi_power_save: true

# Display configuration
display_configuration:
  enabled: true

  # Display mode (hdmi, dsi, headless)
  display_mode: "hdmi" # hdmi, dsi, headless

  # Resolution settings
  hdmi_resolution: "1920x1080"
  hdmi_refresh_rate: 60

  # Console settings
  console_font: "Lat15-TerminusBold14"
  console_blanking: 300 # seconds

# Storage optimization
storage_optimization:
  enabled: true

  # Filesystem optimizations
  mount_options:
    ext4: "defaults,noatime,discard"
    tmpfs_size: "512M"

  # Swap configuration
  swap:
    enabled: false # Disable swap on embedded storage
    swappiness: 1 # Minimal swapping if enabled

  # Log optimization
  log_to_ram: true
  log_ram_size: "100M"

# Network optimization for embedded
network_optimization:
  enabled: true

  # Network interface optimization
  interface_optimization: true

  # WiFi configuration
  wifi:
    power_management: false
    regulatory_domain: "US"

  # Ethernet optimization
  ethernet:
    optimization: true
    flow_control: true

# Security settings for embedded device
security_settings:
  enabled: true

  # Firewall configuration
  firewall:
    enabled: true
    default_policy: "deny"
    allowed_ports:
      - 22 # SSH
      - 9090 # opi-setup API
      - 41641 # Tailscale

  # System hardening
  hardening:
    disable_unused_filesystems: true
    kernel_hardening: true
    network_hardening: true

# Boot optimization
boot_optimization:
  enabled: true

  # Boot performance
  boot_timeout: 3

  # Services to disable for faster boot
  disable_services:
    - bluetooth
    - cups
    - avahi-daemon
    - whoopsie
    - kerneloops
    - accounts-daemon
    - fwupd

  # Services to enable
  enable_services:
    - ssh
    - systemd-timesyncd
    - systemd-resolved
