---
all:
  vars:
    # Environment and project identification
    target_env: "alpr-prod"
    deployment_environment: "production"
    oa_environment:
      name: "alpr-prod"
      stage: "production"

    # ALPR production-specific configuration
    alpr:
      monitor_interval: 10
      detection_threshold: 0.9
      backup_enabled: true
      log_retention_days: 30

  children:
    # Environment group
    production:
      children:
        # Project group
        alpr_project:
          children:
            macos:
              hosts:
                # Placeholder for ALPR production devices
                # alpr-prod-001:
                #   ansible_host: 100.200.200.200
                #   ansible_user: admin
                #   ansible_port: 22
                #   ansible_become_password: "{{ vault_sudo_passwords['alpr-prod-001'] }}"
                #   cam_id: "alpr-cam-001"
            ubuntu_servers:
              hosts:
                # Placeholder for Ubuntu servers if needed