---
# Tasks for deploying the macOS API

- name: Ensure orangead directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /usr/local/orangead
    - /usr/local/orangead/macos-api
    - /usr/local/orangead/macos-api/logs
  become: true

- name: Copy macOS API files
  synchronize:
    src: "{{ playbook_dir }}/macos-api/"
    dest: /usr/local/orangead/macos-api/
    delete: no
    rsync_opts:
      - "--exclude=.venv"
      - "--exclude=__pycache__"
      - "--exclude=.git"
      - "--exclude=.gitignore"
  become: true

- name: Check if virtual environment needs rebuilding
  stat:
    path: /usr/local/orangead/macos-api/.venv/rebuild_needed
  register: rebuild_flag
  become: true

- name: Remove existing virtual environment if rebuild needed
  file:
    path: /usr/local/orangead/macos-api/.venv
    state: absent
  become: true
  when: rebuild_flag.stat.exists | default(false)

- name: Create Python virtual environment
  shell: |
    cd /usr/local/orangead/macos-api
    python3 -m venv .venv
    source .venv/bin/activate
    pip install --upgrade pip
  args:
    creates: /usr/local/orangead/macos-api/.venv/bin/activate
  become: true

- name: Install uv package manager
  shell: |
    cd /usr/local/orangead/macos-api && \
    source .venv/bin/activate && \
    pip install uv
  become: true
  changed_when: false

- name: Install NumPy first to ensure compatibility
  shell: |
    cd /usr/local/orangead/macos-api && \
    source .venv/bin/activate && \
    python -m uv pip install 'numpy<2.0.0'
  become: true
  changed_when: false

- name: Install remaining dependencies with uv
  shell: |
    cd /usr/local/orangead/macos-api && \
    source .venv/bin/activate && \
    python -m uv pip install -r requirements.txt
  become: true
  changed_when: false

- name: Copy OpenCV verification script
  copy:
    src: verify_opencv.py
    dest: /usr/local/orangead/macos-api/verify_opencv.py
    mode: '0755'
  become: true

- name: Verify OpenCV installation
  shell: |
    cd /usr/local/orangead/macos-api && \
    source .venv/bin/activate && \
    python3 ./verify_opencv.py
  register: opencv_check
  changed_when: false
  become: true
  ignore_errors: true  # Don't fail the playbook if verification fails

- name: Create rebuild flag if OpenCV verification fails
  file:
    path: /usr/local/orangead/macos-api/.venv/rebuild_needed
    state: touch
    mode: '0644'
  become: true
  when: opencv_check.rc != 0

- name: Remove rebuild flag if OpenCV verification succeeds
  file:
    path: /usr/local/orangead/macos-api/.venv/rebuild_needed
    state: absent
  become: true
  when: opencv_check.rc == 0

- name: Display OpenCV installation status
  debug:
    var: opencv_check.stdout_lines
  when: opencv_check.stdout_lines is defined

- name: Create _orangead user for running the API service
  user:
    name: _orangead
    system: yes
    shell: /usr/bin/false
    home: /usr/local/orangead
    createhome: no
  become: true

- name: Set ownership of orangead directories
  file:
    path: "{{ item }}"
    state: directory
    owner: _orangead
    group: staff
    recurse: yes
  loop:
    - /usr/local/orangead/macos-api
  become: true

- name: Create launchd plist for macOS API
  template:
    src: com.orangead.macosapi.plist.j2
    dest: /Library/LaunchDaemons/com.orangead.macosapi.plist
    owner: root
    group: wheel
    mode: '0644'
  become: true
  notify: reload macosapi service

- name: Ensure screenshot directory exists
  file:
    path: /tmp/screenshots
    state: directory
    mode: '0755'
    owner: _orangead
    group: staff
  become: true

- name: Configure firewall to allow API port
  command: |
    /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/local/orangead/macos-api/.venv/bin/python3
  become: true
  ignore_errors: true  # Some systems might not have firewall enabled

- name: Load macOS API service
  command: launchctl load -w /Library/LaunchDaemons/com.orangead.macosapi.plist
  become: true
  ignore_errors: true  # In case it's already loaded
