---
# macOS API service configuration
# Handles LaunchAgent setup and service management

- name: Ensure LaunchAgents directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Library/LaunchAgents"
    state: directory
    owner: "{{ ansible_user }}"
    group: staff
    mode: "0755"
  become: true

- name: Check existing LaunchAgent configuration
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/Library/LaunchAgents/com.orangead.macosapi.plist"
  register: existing_plist

- name: Create LaunchAgent configuration
  ansible.builtin.template:
    src: com.orangead.macosapi.plist.j2
    dest: "{{ ansible_user_dir }}/Library/LaunchAgents/com.orangead.macosapi.plist"
    owner: "{{ ansible_user }}"
    group: staff
    mode: "0644"
  register: plist_creation

- name: Stop existing service before configuration update
  ansible.builtin.shell: |
    launchctl bootout gui/$(id -u)/com.orangead.macosapi 2>/dev/null || true
  when: existing_plist.stat.exists and plist_creation.changed

- name: Load and start macOS API service
  ansible.builtin.shell: |
    launchctl bootstrap gui/$(id -u) {{ ansible_user_dir }}/Library/LaunchAgents/com.orangead.macosapi.plist
    launchctl enable gui/$(id -u)/com.orangead.macosapi
    launchctl kickstart gui/$(id -u)/com.orangead.macosapi
  register: service_start

- name: Wait for service to initialize
  ansible.builtin.wait_for:
    timeout: 5
    sleep: 1
  delegate_to: localhost

- name: Verify service is running
  ansible.builtin.shell: |
    set -o pipefail
    launchctl print gui/$(id -u)/com.orangead.macosapi 2>/dev/null | grep "state = running" || echo "not_running"
  register: service_verification
  changed_when: false

- name: Display service status
  ansible.builtin.debug:
    msg: |
      macOS API Service Status:
      - Configuration: {{ 'Updated' if plist_creation.changed else 'No changes' }}
      - Service: {{ 'Running' if 'state = running' in service_verification.stdout else 'Not running' }}
      - Status: {{ 'SUCCESS' if 'state = running' in service_verification.stdout else 'FAILED' }}