---
all:
  vars:
    target_env: production
    ansible_python_interpreter: /usr/bin/python3

  children:
    macos:
      hosts:
        b3:
          ansible_host: 100.85.7.91
          ansible_user: admin
