---
# Ubuntu Docker role defaults

# Docker installation
ubuntu_docker_install_method: "repository" # repository, convenience, manual
ubuntu_docker_version: "latest" # Specific version or 'latest'
ubuntu_docker_channel: "stable" # stable, test, edge
ubuntu_docker_install_compose: true
ubuntu_docker_compose_version: "v2.24.6"

# Docker daemon configuration
ubuntu_docker_daemon_config:
  log-driver: "json-file"
  log-opts:
    max-size: "100m"
    max-file: "3"
  storage-driver: "overlay2"
  live-restore: true
  experimental: false
  userland-proxy: false
  default-ulimits:
    memlock:
      hard: -1
      soft: -1
    nofile:
      hard: 1048576
      soft: 1048576

# Docker service management
ubuntu_docker_service_enabled: true
ubuntu_docker_service_state: "started"
ubuntu_docker_restart_handler_state: "restarted"

# Docker users (users to be added to docker group)
ubuntu_docker_users:
  - "{{ ansible_user }}"

# Docker network configuration
ubuntu_docker_networks: []
# Example:
# docker_networks:
#   - name: "orangead"
#     driver: "bridge"
#     ipam_config:
#       - subnet: "172.20.0.0/16"

# Docker volumes
ubuntu_docker_volumes: []
# Example:
# docker_volumes:
#   - name: "orangead-data"
#     driver: "local"

# Docker registry configuration
ubuntu_docker_registries: []
# Example:
# docker_registries:
#   - url: "https://registry.example.com"
#     username: "user"
#     password: "pass"

# Docker security options
ubuntu_docker_security_options:
  - "no-new-privileges:true"
  - "seccomp:unconfined"

# Docker system cleanup
ubuntu_docker_prune_enabled: true
ubuntu_docker_prune_schedule: "0 3 * * 0" # Weekly at 3 AM on Sunday

# Performance tuning
ubuntu_docker_performance_tuning:
  enabled: true
  max_concurrent_downloads: 3
  max_concurrent_uploads: 5
  max_download_attempts: 5
