---
# Runtime versions
python:
  version: "3.11.11"
node:
  version: "22.11.0"

# Feature toggles
configure:
  tailscale: true
  pyenv: true
  node: true

# Environment-specific features
oa_environment:
  name: "staging"
  allow_experimental: true
  allow_server_optimizations: true
  allow_destructive_operations: true
  allow_tailscale_changes: true

# System packages
system:
  homebrew:
    packages:
      - go
      - git
      - wget
      - jq
      - btop
      - httpie
      - curl
      - telnet
      - util-linux
      - fish

# Tracker configuration
tracker:
  repository_url: "https://github.com/oa-device/oaTracker.git"
  default_yolo_source: 0
  default_model: "yoloe-11s-seg-custom.pt"
  server_port: 8080

# Dashboard configuration
dashboard:
  url: "http://100.79.103.84"
