---
# Runtime versions
python:
  version: "3.10.11"
node:
  version: "22.11.0"

# Feature toggles
configure:
  tailscale: true
  pyenv: true
  node: true

# System packages
system:
  homebrew:
    packages:
      - go
      - git
      - wget
      - jq
      - btop
      - httpie
      - curl
      - telnet
