---
# Configuration for staging environment
# Used for development and testing purposes

# Runtime versions for Python and Node.js
pyenv_default_version: "3.10.11"
node_version: "20.18.0"

# Security settings - relaxed for development convenience
ansible_host_key_checking: false
debug_mode: false
verify_ssl: false

# Infrastructure components to be configured
configure_tailscale: true
configure_pyenv: true
configure_node: true

# System packages installed via Homebrew
# Includes additional development utilities
homebrew_installed_packages:
  - go
  - git
  - wget
  - jq
  - btop
  - httpie
  - curl
  - telnet
