---
all:
  vars:
    # Environment and project identification
    target_env: "f1-preprod"
    oa_environment:
      name: "f1-preprod"
      stage: "preprod"

  children:
    # Environment group
    preprod:
      children:
        # Project group
        f1_project:
          children:
            macos:
              hosts:
                f1-ca-010:
                  ansible_host: 100.71.210.2
                  ansible_user: admin
                  ansible_port: 22
                  ansible_become_password: "{{ vault_sudo_passwords['f1-ca-010'] }}"
                  cam_id: "11111111-1111-1111-1111-111111111111"
                m4-ca-001:
                  ansible_host: 100.77.175.17
                  ansible_user: admin
                  ansible_port: 22
                  ansible_become_password: "{{ vault_sudo_passwords['m4-ca-001'] }}"
                  cam_id: "22222222-2222-2222-2222-222222222222"