---
# Player Role Defaults

# Player configuration - Optimized for kiosk mode deployment
player:
  enabled: false
  video_source: "{{ ansible_user_dir }}/orangead/videos"
  loop_mode: true
  dual_screen: true # Default to dual-screen kiosk mode
  health_check: true
  restart_on_failure: true
  autostart: true

  # Display management for kiosk-style deployment
  system_volume_muted: true # System-wide mute (handled by base role)
  hide_cursor: true # Hide cursor for clean display
  black_background: true # Set desktop background to black (handled by base role)
  disable_screensaver: true # Prevent screensaver activation (handled by base role)

  # Videos configuration - flexible array of video objects
  videos:
    - name: "Jazz_video.webm"
      display: 1
      enabled: true
      loop: true
  # Future videos can be added here:
  # - name: "another_video.mp4"
  #   display: 2
  #   enabled: false
  #   loop: false

  # Display configuration - Always fullscreen for kiosk mode
  fullscreen: true # Always fullscreen, no windowed fallback

  # Player settings - MPV specific
  player_binary: "/opt/homebrew/bin/mpv"
  log_level: "info"
  log_file: "{{ ansible_user_dir }}/orangead/logs/oemplayer.log"

  # LaunchAgent configuration
  service_name: "com.orangead.oemplayer"
  service_user: "{{ ansible_user }}"
  service_keep_alive: true
  service_run_at_load: true

  # Health monitoring
  health_check_interval: 60 # seconds - less aggressive for MPV
  restart_attempts: 3
  restart_delay: 10 # seconds

# Video file management
video_files:
  # Auto-discover videos from role files/ directory
  auto_discover: true
  # Supported video formats
  supported_formats:
    - ".webm"
    - ".mp4"
    - ".mov"
    - ".avi"
    - ".mkv"
  # Download configuration (for external video sources)
  download_enabled: false
  download_url: ""
  backup_enabled: true
  backup_retention_days: 7

# Project-specific configurations (can be overridden in inventory)
project_configs:
  f1:
    videos:
      - name: "f1-highlights.mp4"
        display: 1
        enabled: true
        loop: true
      - name: "f1-race-replay.mp4"
        display: 2
        enabled: false
        loop: true
    dual_screen: true

  alpr:
    videos:
      - name: "alpr-demo.mp4"
        display: 1
        enabled: true
        loop: true
    dual_screen: false

  spectra:
    videos:
      - name: "Jazz_video.webm"
        display: 1
        enabled: true
        loop: true
      - name: "Jazz_video.webm"
        display: 2
        enabled: true
        loop: true
    dual_screen: true # Kiosk mode
    fullscreen: true # Always fullscreen
    system_volume_muted: true # System-wide mute (handled by base role)
    hide_cursor: true # Hide cursor for kiosk mode (handled by base role)
    black_background: true # Set desktop to black (handled by base role)
    disable_screensaver: true # Prevent screensaver (handled by base role)

  # Default configuration for any project - Kiosk mode defaults
  default:
    videos:
      - name: "Jazz_video.webm"
        display: 1
        enabled: true
        loop: true
    dual_screen: true # Default to dual-screen kiosk mode
    fullscreen: true # Always fullscreen
