---
# Cleanup old unused files from previous player implementations
# NOTE: This cleanup is only for development/staging environments during migration from Python to MPV
# It should be skipped in production environments to avoid unnecessary file operations

# File cleanup only - service will continue running during deployment
# Service transition happens later after new files are deployed
- name: Log deployment strategy
  ansible.builtin.debug:
    msg: |
      Blue-green deployment: Keeping current service running during file deployment.
      Service transition will happen after new files are ready to minimize downtime.
  tags: ["player", "cleanup", "info"]

- name: Development cleanup of old player implementations
  when:
    - player.development_cleanup | default(false)
    - oa_environment.name | default('') | regex_search('dev|development|staging|preprod')
  block:
    - name: Remove old Python/VLC player implementation files
      ansible.builtin.file:
        path: "{{ player.video_source }}/{{ item }}"
        state: absent
      loop:
        - "oaplayer.py" # Old 727-line Python player
        - "python_video_player.py" # Legacy Python player
        - "player_config.json" # Old JSON configuration
        - "player.sh" # Old shell wrapper
        - "scripts/player.sh" # Old shell wrapper in scripts
        - "scripts/start_player.sh" # Complex dual-screen launcher
        - ".venv" # Python virtual environment
      failed_when: false

    - name: Remove old health check files if using new implementation
      ansible.builtin.file:
        path: "{{ player.video_source }}/{{ item }}"
        state: absent
      loop:
        - "health_check.sh"
        - "scripts/health_check.sh"
      when: not player.legacy_health_check | default(false)
      failed_when: false

    - name: Remove old LaunchAgent files for previous implementations
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/Library/LaunchAgents/{{ item }}"
        state: absent
      loop:
        - "com.orangead.player.plist" # Old service name
        - "com.orangead.player.health.plist" # Old health monitoring
      failed_when: false

    - name: Clean up old log files with different naming
      ansible.builtin.file:
        path: "{{ player.video_source }}/logs/{{ item }}"
        state: absent
      loop:
        - "player.log"
        - "player.stdout.log"
        - "player.stderr.log"
        - "health_check.log"
        - "health_check_error.log"
      failed_when: false

    - name: Log cleanup completion
      ansible.builtin.debug:
        msg: "Development cleanup completed for environment: {{ oa_environment.name | default('unknown') }}"

- name: Skip cleanup in production
  ansible.builtin.debug:
    msg: "Skipping development cleanup in production environment: {{ oa_environment.name | default('production') }}"
  when:
    - not (player.development_cleanup | default(false))
    - not (oa_environment.name | default('') | regex_search('dev|development|staging|preprod'))
