---
- name: Configure MPV player service
  block:
    - name: Deploy only required video files based on inventory configuration
      ansible.builtin.copy:
        src: "{{ role_path }}/files/{{ video_item.name }}"
        dest: "{{ player.video_source }}/{{ video_item.name }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user_group | default('staff') }}"
        mode: "0644"
      loop: "{{ player.videos | default([]) | selectattr('enabled', 'equalto', true) | list }}"
      loop_control:
        loop_var: video_item
      when:
        - player.videos is defined and player.videos | length > 0
        - video_item.name | regex_search('\.(webm|mp4|mov|avi|mkv)$')

    - name: Deploy OrangeAd MPV player script
      ansible.builtin.template:
        src: oemplayer.sh.j2
        dest: "{{ player.video_source }}/oemplayer.sh"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user_group | default('staff') }}"
        mode: "0755"

    - name: Create player LaunchAgent plist
      ansible.builtin.template:
        src: com.orangead.player.plist.j2
        dest: "{{ ansible_user_dir }}/Library/LaunchAgents/{{ player.service_name }}.plist"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user_group | default('staff') }}"
        mode: "0644"

    - name: Log file deployment completion
      ansible.builtin.debug:
        msg: |
          File deployment completed successfully:
          - Video files: {{ player.videos | default([]) | selectattr('enabled', 'equalto', true) | list | length }} deployed
          - Player script: oemplayer.sh deployed
          - LaunchAgent plist: {{ player.service_name }}.plist ready
          - Service transition will happen next (minimal downtime)

    - name: Verify all required files are in place
      ansible.builtin.stat:
        path: "{{ player.video_source }}/{{ video_item.name }}"
      loop: "{{ player.videos | default([]) | selectattr('enabled', 'equalto', true) | list }}"
      loop_control:
        loop_var: video_item
      register: video_files_final_check
      when: player.videos is defined and player.videos | length > 0

    - name: Validate file deployment readiness
      ansible.builtin.fail:
        msg: "Required video file missing: {{ video_item.video_item.name }}"
      loop: "{{ video_files_final_check.results | default([]) }}"
      loop_control:
        loop_var: video_item
      when:
        - video_files_final_check.results is defined
        - not video_item.stat.exists
