---
- name: Install MPV video player dependencies
  block:
    - name: Check if MPV is installed
      ansible.builtin.shell: |
        export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
        mpv --version
      register: mpv_check
      failed_when: false
      changed_when: false

    - name: Install MPV via Homebrew
      ansible.builtin.shell: |
        export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
        brew install mpv
      when: mpv_check.rc != 0
      register: mpv_install_result
      changed_when: true

    - name: Verify MPV installation
      ansible.builtin.shell: |
        export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
        mpv --version | head -1
      register: mpv_version
      changed_when: false

    - name: Log MPV installation status
      ansible.builtin.debug:
        msg: |
          MPV Installation Status:
          - MPV Version: {{ mpv_version.stdout }}
          - Installation: {{ 'Already installed' if mpv_check.rc == 0 else 'Newly installed' }}
          - Note: MPV provides native dual-screen support with --screen=N

    - name: Check display configuration
      ansible.builtin.shell: |
        # Try multiple methods to detect displays
        if command -v system_profiler >/dev/null 2>&1; then
          display_count=$(system_profiler SPDisplaysDataType 2>/dev/null | grep -c "Resolution:" || echo "0")
          if [ "$display_count" -eq 0 ]; then
            # Fallback: try counting displays via system_profiler differently
            display_count=$(system_profiler SPDisplaysDataType 2>/dev/null | grep -c "Display Type:" || echo "1")
          fi
        else
          display_count="1"
        fi
        echo "$display_count"
      register: display_count
      changed_when: false
      failed_when: false

    - name: Log display configuration
      ansible.builtin.debug:
        msg: "Found {{ display_count.stdout }} display(s) configured"

    - name: Warn if dual screen requested but not available
      ansible.builtin.debug:
        msg: "WARNING: Dual screen requested but only {{ display_count.stdout }} display(s) detected"
      when:
        - player.dual_screen | default(false)
        - display_count.stdout | int < 2

    - name: Check Spectra dual-screen requirements
      ansible.builtin.debug:
        msg: "INFO: Spectra project requires dual-screen setup. Detected {{ display_count.stdout }} display(s)."
      when:
        - oa_environment.project | default('default') == 'spectra'

    - name: Fail if Spectra project lacks dual displays
      ansible.builtin.fail:
        msg: "ERROR: Spectra project requires exactly 2 displays, but {{ display_count.stdout }} detected. Please connect a second display."
      when:
        - oa_environment.project | default('default') == 'spectra'
        - display_count.stdout | int != 2
