---
# Ubuntu Python Role Defaults
# Python environment setup for Ubuntu servers

# Python version management
python_version: "3.11"
install_pyenv: true
install_system_python: true

# Package managers
install_uv: true  # Fast Python package manager
install_pip: true

# Development tools
install_dev_packages: true
dev_packages:
  - python3-dev
  - python3-pip
  - python3-venv
  - python3-setuptools
  - python3-wheel
  - build-essential
  - libssl-dev
  - libffi-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - libncursesw5-dev
  - libgdbm-dev
  - liblzma-dev
  - tk-dev
  - uuid-dev

# PyEnv configuration
pyenv_root: "{{ ansible_user_dir }}/.pyenv"
pyenv_install_python_versions:
  - "{{ python_version }}"

# Virtual environment settings
create_default_venv: false  # ML workstation role will handle this
default_venv_name: "ml-env"

# PATH configuration
update_shell_profile: true
shell_profiles:
  - "{{ ansible_user_dir }}/.bashrc"
  - "{{ ansible_user_dir }}/.zshrc"