---
all:
  vars:
    target_env: pre-prod
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_ssh_pipelining: true
    ansible_become_method: sudo

  children:
    macos:
      hosts:
        f1-ca-010:
          ansible_host: 100.71.210.2
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-010'] | default(vault_default_sudo_password) }}"
          cam_id: "11111111-1111-1111-1111-111111111111"
