---
# OrangePi base handlers

- name: Reboot system
  ansible.builtin.reboot:
    reboot_timeout: 300
    connect_timeout: 20
    test_command: uptime
  become: true
  listen: "reboot system"

- name: Reload udev
  ansible.builtin.command: udevadm control --reload-rules && udevadm trigger
  become: true
  listen: "reload udev"

- name: Restart cpufrequtils
  ansible.builtin.systemd:
    name: cpufrequtils
    state: restarted
    enabled: true
  become: true
  listen: "restart cpufrequtils"

- name: Restart thermald
  ansible.builtin.systemd:
    name: thermald
    state: restarted
    enabled: true
  become: true
  listen: "restart thermald"

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  become: true
  listen: "reload sysctl"
