---
#SPDX-License-Identifier: MIT-0
# defaults file for roles/macos/tracker

# Deploy tracker API alongside tracker (simple and efficient approach)
macos_deploy_tracker_api: true

# Git branch configuration - can be overridden per device
macos_tracker_git_branch: "{{ tracker.git_version | default('main') }}"
