---
# Tailscale cleanup tasks
# Handles cleanup of existing Tailscale installations and services

- name: Get user ID for Tailscale service management
  ansible.builtin.command: id -u {{ ansible_user }}
  register: user_id_result
  changed_when: false
  failed_when: false
  become: true

- name: Stop and disable any user-level Tailscale service (homebrew.mxcl.tailscale)
  ansible.builtin.command: "launchctl bootout gui/{{ user_id_result.stdout }}/homebrew.mxcl.tailscale"
  become: true # Needs to operate on the user's launchd domain, but as root to do so
  register: bootout_result
  failed_when: false
  changed_when: bootout_result.rc == 0
  when: user_id_result.rc == 0 and user_id_result.stdout != ""

- name: Remove user-level Tailscale plist if it exists
  ansible.builtin.file:
    path: "/Users/{{ ansible_user }}/Library/LaunchAgents/homebrew.mxcl.tailscale.plist"
    state: absent
  become: true # Ensure root can delete it even if perms are weird

- name: Pre-cleanup - Stop and remove any existing system-level Tailscale daemon service definition
  ansible.builtin.command: launchctl bootout system /Library/LaunchDaemons/com.tailscale.tailscaled.plist
  become: true
  failed_when: false
  changed_when: false

- name: Pre-cleanup - Remove existing system-level Tailscale daemon plist file
  ansible.builtin.file:
    path: /Library/LaunchDaemons/com.tailscale.tailscaled.plist
    state: absent
  become: true

- name: Pre-cleanup - Check for running tailscaled processes
  ansible.builtin.shell: pgrep tailscaled || echo "not_running"
  become: true
  register: tailscaled_process_check
  changed_when: false

- name: Pre-cleanup - Kill any lingering tailscaled processes
  ansible.builtin.command: pkill tailscaled
  become: true
  register: tailscaled_kill_result
  failed_when: false
  changed_when: tailscaled_kill_result.rc == 0
  when: tailscaled_process_check.stdout != "not_running"

- name: Pre-cleanup - Remove Tailscale.app if it exists (from old Cask install)
  ansible.builtin.file:
    path: /Applications/Tailscale.app
    state: absent
  become: true
