---
# Tailscale VPN setup for macOS
# Modular task orchestration for improved maintainability and idempotency

# Prerequisites and Go environment setup
- name: Setup prerequisites and Go environment
  ansible.builtin.include_tasks: setup_prerequisites.yml
  tags: ["tailscale", "prerequisites", "go"]

# Cleanup existing installations
- name: Cleanup existing Tailscale installations
  ansible.builtin.include_tasks: cleanup_existing.yml
  tags: ["tailscale", "cleanup"]

# Install Tailscale binaries
- name: Install Tailscale binaries
  ansible.builtin.include_tasks: install_binaries.yml
  tags: ["tailscale", "install", "binaries"]

# Configure Tailscale daemon service
- name: Configure Tailscale service
  ansible.builtin.include_tasks: service_config.yml
  tags: ["tailscale", "service", "daemon"]

# Authenticate and connect
- name: Authenticate Tailscale connection
  ansible.builtin.include_tasks: authenticate.yml
  tags: ["tailscale", "auth", "connection"]

# Verify final connection status
- name: Verify Tailscale connection
  ansible.builtin.include_tasks: verify_connection.yml
  tags: ["tailscale", "verify", "status"]