all:
  vars:
    target_env: staging
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_ssh_pipelining: true
    ansible_become_method: sudo

  children:
    macos:
      hosts:
        kai-macVM-1:
          ansible_host: 192.168.64.3
          ansible_user: admin
          ansible_port: 22
        kai-macVM-2:
          ansible_host: 192.168.64.4
          ansible_user: admin
          ansible_port: 22
