---
all:
  vars:
    target_env: staging
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_ssh_pipelining: true
    ansible_become_method: sudo

  children:
    macos:
      hosts:
        b2:
          ansible_host: 192.168.1.23
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords.b2 | default(vault_default_sudo_password) }}"
        b3:
          ansible_host: 192.168.1.218
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords.b3 | default(vault_default_sudo_password) }}"
