---
all:
  vars:
    target_env: staging
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_ssh_pipelining: true
    ansible_become_method: sudo

  children:
    macos:
      hosts:
        f1-ca-001:
          ansible_host: 192.168.1.148
          ansible_user: studio
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-001'] | default(vault_default_sudo_password) }}"
          cam_id: "5e2b80e0-b554-4ee4-99a6-2b1b05c2c656"
        f1-ca-011:
          ansible_host: 192.168.1.177
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-011'] | default(vault_default_sudo_password) }}"
          cam_id: "0d0b831c-740e-421a-b2d2-5d42dcef030f"
        f1-ca-012:
          ansible_host: 192.168.1.231
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-012'] | default(vault_default_sudo_password) }}"
          cam_id: "2f68e7d5-d0c1-4ee8-a273-bab7619b9c22"
        f1-ca-013:
          ansible_host: 192.168.1.23
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-013'] | default(vault_default_sudo_password) }}"
          cam_id: "e1109807-d70b-4f79-ad2e-88b439903235"
        f1-ca-014:
          ansible_host: 192.168.1.218
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-014'] | default(vault_default_sudo_password) }}"
          cam_id: "1ec0b062-a1e6-46b8-bfb0-9ab3ac45eb45"
        f1-ca-015:
          ansible_host: 192.168.1.232
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-015'] | default(vault_default_sudo_password) }}"
          cam_id: "f5f9b8d0-6048-4cbb-8fb7-39df676733a0"
