all:
  vars:
    environment: staging
    ansible_python_interpreter: /usr/bin/python3

  children:
    macos:
      hosts:
        b3:
          ansible_host: 192.168.2.9
          ansible_user: admin
