---
all:
  vars:
    target_env: staging
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_ssh_pipelining: true
    ansible_become_method: sudo

  children:
    macos:
      hosts:
        kai-macVM:
          ansible_host: 192.168.2.45
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['kai-macVM'] | default(vault_default_sudo_password) }}"
          cam_id: "kai-macVM-dummy"
