---
all:
  vars:
    target_env: staging
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_ssh_pipelining: true
    ansible_become_method: sudo

  children:
    macos:
      hosts:
        f1-ca-001:
          ansible_host: 192.168.1.201
          ansible_user: studio
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-001'] | default(vault_default_sudo_password) }}"
          cam_id: "5e2b80e0-b554-4ee4-99a6-2b1b05c2c656"
        f1-ca-002:
          ansible_host: 192.168.1.202
          ansible_user: ek003
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-002'] | default(vault_default_sudo_password) }}"
          cam_id: "1e776547-5c26-4292-a4ce-068260f28bff"
        f1-ca-003:
          ansible_host: 192.168.1.203
          ansible_user: ek002
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-003'] | default(vault_default_sudo_password) }}"
          cam_id: "459c9094-809c-4910-8962-aaac0b116c11"
        f1-ca-004:
          ansible_host: 192.168.1.204
          ansible_user: ek001
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-004'] | default(vault_default_sudo_password) }}"
          cam_id: "5cc648e6-6767-4d34-ba76-04a3501de7f0"
        f1-ca-005:
          ansible_host: 192.168.1.205
          ansible_user: ek000
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-005'] | default(vault_default_sudo_password) }}"
          cam_id: "ac20dace-7838-4f10-ac6f-e3b45770a6af"
        f1-ca-006:
          ansible_host: 192.168.1.230
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-006'] | default(vault_default_sudo_password) }}"
          cam_id: "f1-ca-006-dummy"
        f1-ca-007:
          ansible_host: 192.168.1.207
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-007'] | default(vault_default_sudo_password) }}"
          cam_id: "bac0f58a-e190-484c-b718-6b40e10f9e11"
        f1-ca-008:
          ansible_host: 192.168.1.208
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-008'] | default(vault_default_sudo_password) }}"
          cam_id: "f1-ca-008-dummy"
        f1-ca-009:
          ansible_host: 192.168.1.209
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-009'] | default(vault_default_sudo_password) }}"
          cam_id: "d9349e50-693f-4adc-9ef6-1ff9095da260"
        f1-ca-010:
          ansible_host: 192.168.1.210
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-010'] | default(vault_default_sudo_password) }}"
          cam_id: "f1-ca-010-dummy"
        f1-ca-011:
          ansible_host: 192.168.1.211
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-011'] | default(vault_default_sudo_password) }}"
          cam_id: "0d0b831c-740e-421a-b2d2-5d42dcef030f"
        f1-ca-012:
          ansible_host: 192.168.1.212
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-012'] | default(vault_default_sudo_password) }}"
          cam_id: "2f68e7d5-d0c1-4ee8-a273-bab7619b9c22"
        f1-ca-013:
          ansible_host: 192.168.1.213
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-013'] | default(vault_default_sudo_password) }}"
          cam_id: "e1109807-d70b-4f79-ad2e-88b439903235"
        f1-ca-014:
          ansible_host: 192.168.1.214
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-014'] | default(vault_default_sudo_password) }}"
          cam_id: "1ec0b062-a1e6-46b8-bfb0-9ab3ac45eb45"
        f1-ca-015:
          ansible_host: 192.168.1.215
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-015'] | default(vault_default_sudo_password) }}"
          cam_id: "f5f9b8d0-6048-4cbb-8fb7-39df676733a0"
