---
all:
  vars:
    target_env: staging
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_ssh_pipelining: true
    ansible_become_method: sudo

  children:
    macos:
      hosts:
        kai-vm-001:
          ansible_host: 192.168.64.3
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['kai-vm-001'] | default(vault_default_sudo_password) }}"
          cam_id: "01975bcc-abda-7fb8-8895-b1e86e947ab4"
        kai-vm-002:
          ansible_host: 192.168.64.11
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['kai-vm-002'] | default(vault_default_sudo_password) }}"
          cam_id: "01975bcc-d6ed-7a5e-b1cd-a939b8cbff11"

    ubuntu_servers:
      hosts:
        kampus-rig:
          ansible_host: 192.168.1.247
          ansible_user: kai
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['kampus-rig'] | default(vault_default_sudo_password) }}"
