all:
  vars:
    environment: staging
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_ssh_pipelining: true
    ansible_become_method: sudo

  children:
    macos:
      hosts:
        b3:
          ansible_host: 192.168.2.9
          ansible_user: admin
          ansible_port: 22
