---
all:
  vars:
    target_env: staging
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_ssh_pipelining: true
    ansible_become_method: sudo

  children:
    macos:
      hosts:
        m4-ca-001:
          ansible_host: 192.168.2.47
          ansible_user: admin
          ansible_port: 22
          ansible_become_method: sudo
          ansible_become_password: "{{ lookup('env', 'ANSIBLE_BECOME_PASSWORD_m4_ca_001') | default(lookup('env', 'ANSIBLE_BECOME_PASSWORD_DEFAULT')) }}"
          # Host-specific overrides for ALPR-only setup
          oa_environment:
            name: "staging"
            allow_experimental: true
            allow_server_optimizations: false # Disable watchdog scripts and server optimizations
            allow_destructive_operations: true
            allow_tailscale_changes: true
            deploy_alpr_service: true
          # Skip API and Tracker roles for this host
          skip_roles:
            - "macos/api"
            - "macos/tracker"

    ubuntu_servers:
      hosts:
        kampus-rig:
          ansible_host: 192.168.1.247
          ansible_user: kai
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['kampus-rig'] | default(vault_default_sudo_password) }}"
