---
- name: Configure macOS firewall
  block:
    - name: Check firewall status
      ansible.builtin.command: /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate
      register: firewall_status
      changed_when: false

    - name: Enable macOS firewall
      ansible.builtin.command: /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on
      when: "'Firewall is disabled' in firewall_status.stdout"
      become: true

    - name: Allow signed apps
      ansible.builtin.command: /usr/libexec/ApplicationFirewall/socketfilterfw --setallowsigned on
      become: true

    - name: Allow signed downloaded apps
      ansible.builtin.command: /usr/libexec/ApplicationFirewall/socketfilterfw --setallowsignedapp on
      become: true

    - name: Enable stealth mode
      ansible.builtin.command: /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on
      become: true

    - name: Open specified ports
      ansible.builtin.command: "echo 'pass in proto tcp from any to any port {{ item }}' | pfctl -ef -"
      loop: "{{ open_ports }}"
      become: true

    - name: Restart firewall to apply changes
      ansible.builtin.command: pkill -HUP socketfilterfw
      become: true

    - name: Display firewall status
      ansible.builtin.command: /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate
      register: final_firewall_status
      changed_when: false

    - name: Show firewall status
      ansible.builtin.debug:
        var: final_firewall_status.stdout_lines

  when: configure_firewall | bool
