---
- name: Install and configure monitoring tools
  block:
    - name: Check if Node Exporter is installed
      ansible.builtin.stat:
        path: /usr/local/bin/node_exporter
      register: node_exporter_check

    - name: Download Node Exporter
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.darwin-amd64.tar.gz"
        dest: "/tmp/node_exporter.tar.gz"
      when: not node_exporter_check.stat.exists

    - name: Extract Node Exporter
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "/tmp"
        remote_src: yes
      when: not node_exporter_check.stat.exists

    - name: Move Node Exporter binary
      ansible.builtin.copy:
        src: "/tmp/node_exporter-1.3.1.darwin-amd64/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        mode: '0755'
        remote_src: yes
      become: true
      when: not node_exporter_check.stat.exists

    - name: Create Node Exporter plist file
      ansible.builtin.template:
        src: com.github.prometheus.node_exporter.plist.j2
        dest: /Library/LaunchDaemons/com.github.prometheus.node_exporter.plist
        mode: '0644'
      become: true

    - name: Load Node Exporter service
      ansible.builtin.command: launchctl load -w /Library/LaunchDaemons/com.github.prometheus.node_exporter.plist
      become: true

    - name: Start Node Exporter service
      ansible.builtin.command: launchctl start com.github.prometheus.node_exporter
      become: true

    - name: Clean up temporary files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/node_exporter.tar.gz"
        - "/tmp/node_exporter-1.3.1.darwin-amd64"

    - name: Verify Node Exporter is running
      ansible.builtin.uri:
        url: http://localhost:9100/metrics
        method: GET
      register: node_exporter_check
      ignore_errors: true

    - name: Display Node Exporter status
      ansible.builtin.debug:
        msg: "Node Exporter is {{ 'running' if node_exporter_check.status == 200 else 'not running' }}"

  when: install_monitoring_tools | bool
