---
# Configure SSH settings
- name: Configure SSH
  block:
    # Update SSH configuration file
    - name: Update SSH configuration
      ansible.builtin.template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
        mode: '0644'
      notify: Restart SSH service
      # The template will use variables from default.config.yml

    # Ensure SSH service is running and enabled
    - name: Ensure SSH service is running and enabled
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: yes
  when: configure_ssh | bool
  # This entire block will only run if configure_ssh is set to true in default.config.yml
