---
- name: Configure Tailscale
  block:
    - name: Check if Tailscale is already installed
      ansible.builtin.stat:
        path: /Applications/Tailscale.app
      register: tailscale_installed

    - name: Download Tailscale DMG
      get_url:
        url: "https://pkgs.tailscale.com/stable/Tailscale-{{ tailscale_version }}.dmg"
        dest: "/tmp/Tailscale-{{ tailscale_version }}.dmg"
      when: not tailscale_installed.stat.exists

    - name: Mount Tailscale DMG
      ansible.builtin.command: hdiutil attach "/tmp/Tailscale-{{ tailscale_version }}.dmg"
      when: not tailscale_installed.stat.exists

    - name: Install Tailscale
      ansible.builtin.command: cp -R /Volumes/Tailscale/Tailscale.app /Applications/
      when: not tailscale_installed.stat.exists

    - name: Unmount Tailscale DMG
      ansible.builtin.command: hdiutil detach /Volumes/Tailscale
      when: not tailscale_installed.stat.exists

    - name: Remove Tailscale DMG
      ansible.builtin.file:
        path: "/tmp/Tailscale-{{ tailscale_version }}.dmg"
        state: absent
      when: not tailscale_installed.stat.exists

    - name: Start Tailscale
      ansible.builtin.command: open -a Tailscale
      when: not tailscale_installed.stat.exists

    - name: Wait for Tailscale to start
      ansible.builtin.wait_for:
        path: /var/run/tailscaled.socket
        state: present
        timeout: 30
      when: not tailscale_installed.stat.exists

    - name: Check Tailscale status
      ansible.builtin.command: tailscale status
      register: tailscale_status
      changed_when: false
      ignore_errors: true

    - name: Display Tailscale status
      ansible.builtin.debug:
        var: tailscale_status.stdout_lines
      when: tailscale_status.rc == 0

  when: configure_tailscale | bool
