---
- name: Check if Xcode CLI tools are installed
  ansible.builtin.command: xcode-select -p
  register: xcode_select
  ignore_errors: true
  changed_when: false
  when: 
    - configure_xcode | bool
    - ansible_distribution == 'MacOSX'

- name: Install Xcode CLI tools
  ansible.builtin.command: xcode-select --install
  when: 
    - configure_xcode | bool
    - xcode_select.rc != 0
    - ansible_distribution == 'MacOSX'
