---
# Ubuntu server optimization handlers

- name: Update grub
  ansible.builtin.command: update-grub
  become: true
  listen: "update grub"

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: true
  become: true
  listen: "restart systemd-resolved"

- name: Reload network driver
  ansible.builtin.shell: |
    modprobe -r r8169 || true
    sleep 2
    modprobe r8169
  become: true
  listen: "reload network driver"

- name: Restart networking
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
    daemon_reload: true
  become: true
  listen: "restart networking"
