---
# Ubuntu server optimization handlers

- name: Update grub
  ansible.builtin.command: update-grub
  become: true
  listen: "update grub"

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: true
  become: true
  listen: "restart systemd-resolved"
