---
# Display and screensaver configuration tasks for macOS base setup
# Configures display settings for kiosk/production environments
# NOTE: Power management (sleep) settings moved to system_preferences.yml

- name: No password required after screen saver begins
  ansible.builtin.shell: |
    defaults write com.apple.screensaver askForPassword -int 0
  changed_when: false

- name: No password required after display is turned off
  ansible.builtin.shell: |
    defaults write com.apple.screensaver askForPasswordDelay -int 0
  changed_when: false

- name: Disable screen saver for all users
  ansible.builtin.shell: |
    defaults write /Library/Preferences/com.apple.screensaver idleTime -int 0
  become: true
  changed_when: false

- name: Apply screen saver settings immediately
  ansible.builtin.shell: |
    killall cfprefsd
  failed_when: false
  changed_when: false
