---
# Tasks to enhance zsh shell experience on macOS devices

# Ensure required user directories exist before creating files
- name: Include user directory creation tasks
  ansible.builtin.include_tasks: ../../../common/tasks/ensure_user_directories.yml
  tags: ["shell", "zsh", "setup"]

- name: Enhance zsh shell experience
  tags: ["shell", "zsh", "setup"]
  block:
    - name: Copy zsh enhancement script
      ansible.builtin.copy:
        src: zshrc_enhancement.sh
        dest: "{{ ansible_env.HOME }}/zshrc_enhancement.sh"
        mode: "0755"
      changed_when: false

    - name: Execute zsh enhancement script
      ansible.builtin.shell: |
        {{ ansible_env.HOME }}/zshrc_enhancement.sh
      register: zsh_enhancement
      changed_when: zsh_enhancement.stdout is search('Installing') or zsh_enhancement.stdout is search('enhanced successfully')

    - name: Display enhancement results
      ansible.builtin.debug:
        msg: "{{ zsh_enhancement.stdout_lines }}"

    - name: Clean up enhancement script
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/zshrc_enhancement.sh"
        state: absent
      changed_when: false
