---
# Set up shell configuration first
- name: Configure shell environment
  block:
    - name: Get default shell
      ansible.builtin.command: dscl . -read /Users/{{ ansible_user }} UserShell
      register: user_shell_info
      changed_when: false

    - name: Set shell configuration facts
      ansible.builtin.set_fact:
        shell_config:
          zsh:
            profile_file: .zprofile
            rc_file: .zshrc
          bash:
            profile_file: .bashrc
            rc_file: .bash_profile

    - name: Set shell-specific facts
      ansible.builtin.set_fact:
        user_shell: "{{ user_shell_info.stdout.split('/')[-1] }}"
        shell_profile: "{{ ansible_env.HOME }}/{{ shell_config[user_shell_info.stdout.split('/')[-1]].profile_file }}"
        shell_rc: "{{ ansible_env.HOME }}/{{ shell_config[user_shell_info.stdout.split('/')[-1]].rc_file }}"

    - name: Ensure shell configuration files exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: touch
        mode: "0644"
      loop:
        - "{{ shell_profile }}"
        - "{{ shell_rc }}"

    - name: Configure shell environment
      ansible.builtin.blockinfile:
        path: "{{ item.path }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ item.name }}"
        block: "{{ item.content }}"
      loop:
        - path: "{{ shell_profile }}"
          name: "PATH_CONFIG"
          content: |
            # System PATH configuration
            export PATH="{{ homebrew_prefix }}/bin:$PATH"

            # Homebrew configuration
            eval "$({{ homebrew_prefix }}/bin/brew shellenv)"

            {% if configure.pyenv %}
            # Pyenv configuration
            export PYENV_ROOT="$HOME/.pyenv"
            export PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init -)"
            {% endif %}

            {% if configure.node %}
            # Node.js configuration
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            {% endif %}

        - path: "{{ shell_rc }}"
          name: "SHELL_CONFIG"
          content: |
            # Shell-specific configurations
            export LANG=en_US.UTF-8
            export EDITOR=vim

# Configure passwordless sudo for the ansible_user (admin)
- name: Ensure ansible_user can sudo without a password
  become: true # This task itself needs sudo to modify /etc/sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{ ansible_user }} ALL="
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  tags: ["sudo", "setup"] # Add tags for selective running

# Clean up legacy JPR Launch Agents and Daemons
- name: Clean up legacy JPR services
  block:
    - name: Get list of JPR Launch Agents
      ansible.builtin.shell: |
        launchctl list | grep ca.jpr | awk '{print $3}' || true
      register: jpr_agents
      changed_when: false

    - name: Get list of JPR Launch Daemons
      ansible.builtin.shell: |
        sudo launchctl list | grep ca.jpr | awk '{print $3}' || true
      register: jpr_daemons
      changed_when: false
      become: true

    - name: Unload JPR Launch Agents
      ansible.builtin.shell: |
        launchctl unload "{{ ansible_env.HOME }}/Library/LaunchAgents/{{ item }}.plist"
      loop: "{{ jpr_agents.stdout_lines }}"
      when: jpr_agents.stdout_lines | length > 0
      ignore_errors: true

    - name: Remove JPR Launch Agent files
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/Library/LaunchAgents/{{ item }}.plist"
        state: absent
      loop: "{{ jpr_agents.stdout_lines }}"
      when: jpr_agents.stdout_lines | length > 0

    - name: Unload JPR Launch Daemons
      ansible.builtin.shell: |
        sudo launchctl unload "/Library/LaunchDaemons/{{ item }}.plist"
      loop: "{{ jpr_daemons.stdout_lines }}"
      when: jpr_daemons.stdout_lines | length > 0
      become: true
      ignore_errors: true

    - name: Remove JPR Launch Daemon files
      ansible.builtin.file:
        path: "/Library/LaunchDaemons/{{ item }}.plist"
        state: absent
      loop: "{{ jpr_daemons.stdout_lines }}"
      when: jpr_daemons.stdout_lines | length > 0
      become: true

    - name: Verify JPR cleanup - check remaining agents
      ansible.builtin.shell: |
        launchctl list | grep ca.jpr || echo "No JPR agents found"
      register: remaining_agents
      changed_when: false

    - name: Verify JPR cleanup - check remaining daemons
      ansible.builtin.shell: |
        sudo launchctl list | grep ca.jpr || echo "No JPR daemons found"
      register: remaining_daemons
      changed_when: false
      become: true

    - name: Report JPR cleanup results
      ansible.builtin.debug:
        msg:
          - "JPR Launch Agents cleanup: {{ 'COMPLETE' if 'No JPR agents found' in remaining_agents.stdout else 'INCOMPLETE - ' + remaining_agents.stdout }}"
          - "JPR Launch Daemons cleanup: {{ 'COMPLETE' if 'No JPR daemons found' in remaining_daemons.stdout else 'INCOMPLETE - ' + remaining_daemons.stdout }}"

  tags: ["cleanup", "jpr"]
