---
# macOS base system configuration
# Modular task orchestration for improved maintainability and idempotency

# Essential system preferences
- name: Configure system preferences
  ansible.builtin.include_tasks: system_preferences.yml
  tags: ["base", "system", "preferences"]

# Shell configuration via centralized shell manager
- name: Configure shell environment (Shell Manager)
  ansible.builtin.include_role:
    name: common/shell_manager
  vars:
    shell_manager_overrides: "{{ macos_shell_overrides | default({}) }}"
  tags: ["base", "shell", "shell_manager"]

# Sudo configuration for passwordless operations
- name: Configure sudo permissions
  ansible.builtin.include_tasks: sudo_config.yml
  tags: ["base", "sudo", "setup"]

# Clean up legacy JPR services
- name: Clean up legacy services
  ansible.builtin.include_tasks: legacy_cleanup.yml
  tags: ["base", "cleanup", "jpr"]

# Audio configuration for kiosk environments
- name: Configure audio settings
  ansible.builtin.include_tasks: audio_config.yml
  tags: ["base", "sound", "audio"]

# Display and screensaver configuration
- name: Configure display settings
  ansible.builtin.include_tasks: display_config.yml
  tags: ["base", "screensaver", "display"]

# Kiosk UI configuration
- name: Configure kiosk UI settings
  ansible.builtin.include_tasks: kiosk_ui.yml
  tags: ["base", "kiosk", "ui"]

# Modern desktop and dock configuration
- name: Configure desktop and dock
  ansible.builtin.include_tasks: desktop_config.yml
  tags: ["base", "kiosk", "modern", "desktop"]

# Notification suppression for kiosk mode
- name: Configure notification suppression
  ansible.builtin.include_tasks: notification_config.yml
  tags: ["base", "kiosk", "notifications", "updates"]

# Daily reboot service for system stability
- name: Configure daily reboot service
  ansible.builtin.include_tasks: daily_reboot.yml
  tags: ["base", "reboot", "stability"]
