---
# Shell configuration tasks for macOS base setup
# Handles shell setup, PATH configuration, and shell profiles

- name: Set default shell to zsh
  ansible.builtin.shell: |
    chsh -s /bin/zsh {{ ansible_user }}
  become: true
  changed_when: false

- name: Get default shell
  ansible.builtin.command: dscl . -read /Users/{{ ansible_user }} UserShell
  register: user_shell_info
  changed_when: false

- name: Set shell configuration facts
  ansible.builtin.set_fact:
    shell_config: "{{ macos_shell_config }}"
  changed_when: false

- name: Set shell-specific facts (force zsh)
  ansible.builtin.set_fact:
    user_shell: "zsh"
    shell_profile: "{{ ansible_env.HOME }}/.zprofile"
    shell_rc: "{{ ansible_env.HOME }}/.zshrc"
  changed_when: false

- name: Ensure shell configuration files exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: "0644"
  loop:
    - "{{ shell_profile }}"
    - "{{ shell_rc }}"
  changed_when: false

- name: Configure shell environment
  ansible.builtin.blockinfile:
    path: "{{ item.path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ item.name }}"
    block: "{{ item.content }}"
  loop:
    - path: "{{ shell_profile }}"
      name: "PATH_CONFIG"
      content: |
        # System PATH configuration
        export PATH="{{ macos_system.homebrew.prefix }}/bin:$PATH"

        # Homebrew configuration
        eval "$({{ macos_system.homebrew.prefix }}/bin/brew shellenv)"

        {% if macos_configure.pyenv %}
        # Pyenv configuration
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        {% endif %}

        {% if macos_configure.node %}
        # Node.js configuration
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
        {% endif %}

    - path: "{{ shell_rc }}"
      name: "SHELL_CONFIG"
      content: |
        # Shell-specific configurations
        export LANG=en_US.UTF-8
        export EDITOR=vim
  changed_when: false

# Include zsh enhancement tasks
- name: Include zsh enhancement tasks
  ansible.builtin.include_tasks: enhance_zsh.yml
  tags: ["shell", "zsh", "setup"]