---
# macOS Tracker deployment
# Modular task orchestration for improved maintainability and idempotency

# System setup and prerequisites
- name: System setup and prerequisites
  ansible.builtin.include_tasks: system_setup.yml
  tags: ["tracker", "system", "setup"]

# Directory management and git operations
- name: Directory management and repository setup
  ansible.builtin.include_tasks: directory_mgmt.yml
  tags: ["tracker", "directory", "git"]

# Configuration validation and git checkout
- name: Configuration validation and git setup
  ansible.builtin.include_tasks: config_validation.yml
  tags: ["tracker", "config", "validation"]

# Python environment and dependencies
- name: Python environment setup
  ansible.builtin.include_tasks: python_setup.yml
  tags: ["tracker", "python", "dependencies"]

# Service configuration and LaunchAgent setup
- name: Service configuration and setup
  ansible.builtin.include_tasks: service_setup.yml
  tags: ["tracker", "service", "launchd"]

# Deployment verification and health checks
- name: Deployment verification
  ansible.builtin.include_tasks: verify_deployment.yml
  tags: ["tracker", "verify", "status"]