---
# Ubuntu Docker installation and configuration

- name: Check Docker installation status
  block:
    - name: Check if Docker is already installed
      ansible.builtin.command: docker --version
      register: ubuntu_docker_version_check
      failed_when: false
      changed_when: false

    - name: Check if Docker Compose is already installed
      ansible.builtin.command: docker compose version
      register: ubuntu_docker_compose_version_check
      failed_when: false
      changed_when: false
      when: ubuntu_docker_install_compose

    - name: Set Docker installation flags
      ansible.builtin.set_fact:
        docker_already_installed: "{{ ubuntu_docker_version_check.rc == 0 }}"
        docker_compose_already_installed: "{{ ubuntu_docker_compose_version_check.rc == 0 if ubuntu_docker_install_compose else true }}"

- name: Display Docker installation status
  ansible.builtin.debug:
    msg: |
      Docker Installation Status:
      - Docker Engine: {{ 'Already installed' if docker_already_installed else 'Need installation' }}
      - Docker Compose: {{ 'Already installed' if docker_compose_already_installed else 'Need installation' }}

- name: Install Docker prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: true
  become: true
  when: not docker_already_installed

- name: Create apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true
  when: not docker_already_installed

- name: Install Docker using convenience script (recommended for new Ubuntu releases)
  ansible.builtin.shell: |
    # Remove any existing Docker installations and repositories first
    apt-get remove -y docker docker-engine docker.io containerd runc 2>/dev/null || true
    rm -f /etc/apt/sources.list.d/*docker*.list
    rm -f /etc/apt/keyrings/docker.*
    apt-get update

    # Download and run Docker convenience script
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sh /tmp/get-docker.sh
    rm -f /tmp/get-docker.sh
  become: true
  when: not docker_already_installed

- name: Verify Docker packages are available
  ansible.builtin.shell: |
    apt-cache search docker-ce | head -5
    echo "--- Available docker-ce packages ---"
    apt-cache madison docker-ce | head -3
  register: docker_packages_check
  become: true
  when: not docker_already_installed

- name: Display available Docker packages
  ansible.builtin.debug:
    msg: "{{ docker_packages_check.stdout_lines }}"
  when: not docker_already_installed

- name: Install Docker packages (official method)
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true
  when: not docker_already_installed

# Docker Compose is now installed as a plugin (docker-compose-plugin) in the main installation

- name: Create Docker daemon configuration directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: "0755"
  become: true

- name: Configure Docker daemon
  ansible.builtin.copy:
    content: "{{ ubuntu_docker_daemon_config | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: "0644"
    backup: true
  become: true
  notify: restart docker

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  become: true
  loop: "{{ ubuntu_docker_users }}"
  notify: restart docker

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: "{{ ubuntu_docker_service_enabled }}"
    state: "{{ ubuntu_docker_service_state }}"
    daemon_reload: true
  become: true

- name: Create Docker networks
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver | default('bridge') }}"
    ipam_config: "{{ item.ipam_config | default(omit) }}"
    state: present
  loop: "{{ ubuntu_docker_networks }}"
  when: ubuntu_docker_networks | length > 0

- name: Create Docker volumes
  community.docker.docker_volume:
    name: "{{ item.name }}"
    driver: "{{ item.driver | default('local') }}"
    driver_options: "{{ item.driver_options | default(omit) }}"
    state: present
  loop: "{{ ubuntu_docker_volumes }}"
  when: ubuntu_docker_volumes | length > 0

- name: Configure Docker registry authentication
  community.docker.docker_login:
    registry_url: "{{ item.url }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    state: present
  loop: "{{ ubuntu_docker_registries }}"
  when: ubuntu_docker_registries | length > 0
  no_log: true

- name: Create Docker system cleanup cron job
  ansible.builtin.cron:
    name: "Docker system prune"
    job: "docker system prune -af --volumes > /dev/null 2>&1"
    minute: "{{ ubuntu_docker_prune_schedule.split()[0] }}"
    hour: "{{ ubuntu_docker_prune_schedule.split()[1] }}"
    day: "{{ ubuntu_docker_prune_schedule.split()[2] }}"
    month: "{{ ubuntu_docker_prune_schedule.split()[3] }}"
    weekday: "{{ ubuntu_docker_prune_schedule.split()[4] }}"
    user: root
    state: "{{ 'present' if ubuntu_docker_prune_enabled else 'absent' }}"
  become: true

- name: Verify Docker installation
  block:
    - name: Test Docker installation
      ansible.builtin.command: docker run --rm hello-world
      register: docker_test
      changed_when: false
      become: true

    - name: Test Docker Compose installation
      ansible.builtin.command: docker compose version
      register: docker_compose_test
      changed_when: false
      when: ubuntu_docker_install_compose

    - name: Display Docker verification results
      ansible.builtin.debug:
        msg: |-
          Docker Installation Verification:
          - Docker Engine: {{ 'Working' if docker_test.rc == 0 else 'Failed' }}
          - Docker Compose: {{ 'Working' if docker_compose_test.rc == 0 else 'Failed' if ubuntu_docker_install_compose else 'Not installed' }}
          - Users in docker group: {{ ubuntu_docker_users | join(', ') }}
