---
# SSH key management tasks for macOS

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: "0700"
  become: false # Should run as the ansible_user

- name: Add SSH public key to authorized_keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ vault_ssh_public_key }}"
    state: present
  become: false # Should run as the ansible_user

- name: Define a unique portion of the public key for verification
  ansible.builtin.set_fact:
    # Extracts roughly the middle 60 characters of the Base64 part of an ssh-rsa key
    # This is more robust than grepping the whole key or just the comment
    public_key_fingerprint_segment: >-
      {{ (vault_ssh_public_key.split(' ')[1] | default(''))[100:160] if vault_ssh_public_key and ' ' in vault_ssh_public_key else "INVALID_KEY_FORMAT_IN_VAULT" }}
  when: vault_ssh_public_key is defined and vault_ssh_public_key != ""

- name: Verify SSH key was added
  ansible.builtin.command: "grep -F -- '{{ public_key_fingerprint_segment }}' ~/.ssh/authorized_keys"
  register: key_check
  changed_when: false
  failed_when: false # This task itself should not fail the playbook
  become: false # Run as ansible_user
  when: public_key_fingerprint_segment is defined and public_key_fingerprint_segment != "INVALID_KEY_FORMAT_IN_VAULT"

- name: Show SSH key status
  ansible.builtin.debug:
    msg: "SSH key successfully added to {{ inventory_hostname }} and verified in authorized_keys."
  when: key_check is defined and key_check.rc == 0

- name: Show SSH key error or verification issue
  ansible.builtin.debug:
    msg: "SSH key was likely added by 'authorized_key' module, but 'grep' verification failed for host {{ inventory_hostname }}. Public key segment used for grep:
      '{{ public_key_fingerprint_segment | default('COULD_NOT_EXTRACT_SEGMENT') }}'. Please manually check ~/.ssh/authorized_keys on the target. Possible whitespace/format
      differences in vault vs. file."
  when: key_check is defined and key_check.rc != 0

- name: Notify if public key segment could not be extracted
  ansible.builtin.debug:
    msg: "Could not extract a public key segment for verification from 'vault_ssh_public_key'. Key might be missing or malformed in the vault."
  when: public_key_fingerprint_segment is not defined or public_key_fingerprint_segment == "INVALID_KEY_FORMAT_IN_VAULT"
