---
- name: Restart player
  ansible.builtin.shell: |
    # Stop the service
    launchctl stop {{ player.service_name }} 2>/dev/null || true

    # Wait briefly for service to stop
    sleep 3

    # Kill any remaining MPV processes
    pkill -f mpv || true

    # Wait for processes to terminate
    sleep 2

    # Start the service
    launchctl start {{ player.service_name }} || true
  become: false
  changed_when: false
  failed_when: false

- name: Reload player
  ansible.builtin.shell: |
    launchctl unload "{{ ansible_user_dir }}/Library/LaunchAgents/{{ player.service_name }}.plist" 2>/dev/null || true
    launchctl load "{{ ansible_user_dir }}/Library/LaunchAgents/{{ player.service_name }}.plist"
  become: false
  changed_when: false
  failed_when: false

- name: Stop player
  ansible.builtin.shell: |
    launchctl stop {{ player.service_name }} 2>/dev/null || true
    pkill -f "mpv.*--screen=" 2>/dev/null || true
    pkill -f "oemplayer.sh" 2>/dev/null || true
  become: false
  changed_when: false
  failed_when: false

- name: Start player
  ansible.builtin.shell: |
    launchctl start {{ player.service_name }}
  become: false
  changed_when: false
  failed_when: false
