---
- name: restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
  become: true

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  become: true

- name: reload ufw
  ansible.builtin.service:
    name: ufw
    state: reloaded
  become: true
