---
# System Configuration
# -------------------
macos_system:
  homebrew:
    prefix: "{{ (ansible_architecture == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
    install_path: "{{ (ansible_architecture == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
    packages:
      - git
      - curl
      - wget

# Feature Toggles
# --------------
macos_configure:
  tailscale: true
  pyenv: true
  node: true

# Development Environment
# ---------------------
macos_python:
  version: "3.11.11"
  packages:
    - pip
    - virtualenv

macos_node:
  version: "22.11.0"
  packages:
    - pm2
    - yarn

# Network Configuration
# -------------------
macos_dns:
  enable_magic_dns: true
  preserve_dhcp_dns: true
  tailscale_servers: ["100.100.100.100"]
# Shell Configuration
# -----------------
macos_shell_config:
  zsh:
    rc_file: .zshrc
    profile_file: .zprofile
  bash:
    rc_file: .bashrc
    profile_file: .bash_profile
