---
all:
  vars:
    # Environment and project identification
    target_env: "spectra-preprod"
    deployment_environment: "preprod"
    oa_environment:
      name: "spectra-preprod"
      stage: "preprod"

  children:
    # Environment group
    preprod:
      children:
        # Project group
        spectra_project:
          children:
            macos:
              hosts:
                spectra-ca-001:
                  ansible_host: 100.103.229.95
                  ansible_user: studio
                  ansible_port: 22
                  ansible_become_password: "{{ vault_sudo_passwords['spectra-ca-001'] }}"
                  cam_id: "22222222-2222-2222-2222-222222222222"