---
all:
  vars:
    # Environment and project identification
    target_env: "spectra-prod"
    deployment_environment: "production"
    oa_environment:
      name: "spectra-prod"
      stage: "production"

  children:
    # Project-Environment group (inherits from production, spectra_project, and macos)
    spectra_prod:
      children:
        macos:
          hosts:
            spectra-ca-001:
              ansible_host: 100.103.229.95
              ansible_user: studio
              ansible_port: 22
              ansible_become_password: "{{ vault_sudo_passwords['spectra-ca-001'] }}"
              cam_id: "22222222-2222-2222-2222-222222222222"
            f1-ca-007:
              ansible_host: 100.78.224.4
              ansible_user: admin
              ansible_port: 22
              ansible_become_password: "{{ vault_sudo_passwords['f1-ca-007'] }}"
              cam_id: "bac0f58a-e190-484c-b718-6b40e10f9e11"
            f1-ca-011:
              ansible_host: 100.108.127.23
              ansible_user: admin
              ansible_port: 22
              ansible_become_password: "{{ vault_sudo_passwords['f1-ca-011'] }}"
              cam_id: "0d0b831c-740e-421a-b2d2-5d42dcef030f"
            f1-ca-012:
              ansible_host: 100.67.135.111
              ansible_user: admin
              ansible_port: 22
              ansible_become_password: "{{ vault_sudo_passwords['f1-ca-012'] }}"
              cam_id: "2f68e7d5-d0c1-4ee8-a273-bab7619b9c22"
            f1-ca-016:
              ansible_host: 100.68.254.108
              ansible_user: admin
              ansible_port: 22
              ansible_become_password: "{{ vault_sudo_passwords['f1-ca-016'] }}"
              cam_id: "009a3750-3d03-456c-933f-5e0e035f92de"
