---
- name: Configure MacOS
  hosts: all
  become: true
  vars_files:
    - ../config.yml

  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
    - geerlingguy.mac.dock

  vars:
    homebrew_installed_packages: "{{ common_packages + macos_packages }}"
    homebrew_cask_apps: "{{ macos_applications }}"

  tasks:
    - name: Check if full Xcode is installed
      stat:
        path: /Applications/Xcode.app
      register: xcode_app

    - name: Accept Xcode license
      command: xcodebuild -license accept
      become: true
      when: xcode_app.stat.exists
