---
- name: Configure MacOS
  hosts: all
  become: true
  vars_files:
    - ../config.yml

  tasks:
    - name: Install Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/bin/brew

    - name: Install common packages
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ common_packages }}"

    - name: Install MacOS-specific packages
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ macos_packages }}"

    - name: Install applications via Homebrew Cask
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{ macos_applications }}"

    # Add more MacOS-specific tasks here
