---
# Complete OrangePi Configuration Playbook
# Deploys full OrangeAd embedded stack on OrangePi devices
# NOTE: This is a placeholder - will be fully implemented in Phase 5

- name: Configure OrangePi for OrangeAd - Full Embedded Stack
  hosts: all
  gather_facts: false
  tags: ["orangepi", "full", "embedded"]
  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Debug connection info
      ansible.builtin.debug:
        msg: |
          OrangePi Device Configuration:
          - Host: {{ ansible_host }}
          - User: {{ ansible_user }}
          - Python: {{ ansible_python.executable }}
          - Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}
          - Architecture: {{ ansible_architecture }}
          - Board: {{ ansible_board_name | default('Unknown') }}

    - name: Verify target is ARM-based Linux
      ansible.builtin.fail:
        msg: "This playbook requires ARM-based Linux (Debian/Ubuntu)"
      when:
        - ansible_distribution not in ["Debian", "Ubuntu"]
        - ansible_architecture not in ["aarch64", "armv7l", "arm64"]

    - name: Display implementation status
      ansible.builtin.debug:
        msg: |
          OrangePi Full Stack Implementation Status:
          - Phase 5 Target: Complete OrangePi embedded support
          - Current: Placeholder with basic structure
          - Integration: Will work with existing opi-setup project
          - Components: opi-setup API, system optimization, GPIO

    - name: Environment safety checks
      ansible.builtin.import_tasks: ../tasks/environment_checks.yml
      tags: ["always"]

  roles:
    # Phase 5.2 OrangePi Platform Implementation
    - role: orangepi/base
      tags: ["base", "hardware", "optimization"]

    - role: orangepi/opi_setup
      tags: ["opi-setup", "api", "service"]

    # Future OrangePi roles (Phase 5.2 continuation)
    # - role: orangepi/network
    # - role: orangepi/optimization

  tasks:
    - name: Display OrangePi capabilities
      ansible.builtin.debug:
        msg: |
          OrangePi Full Stack - Phase 5.2 Implementation Status:
          ✅ orangepi/base role - System and hardware optimization
          ✅ orangepi/opi_setup role - FastAPI service deployment
          📋 orangepi/network role - Network and Tailscale (planned)
          📋 orangepi/optimization role - Advanced performance tuning (planned)
          🔄 Integration with existing opi-setup project (ongoing)

  post_tasks:
    - name: Display completion message
      ansible.builtin.debug:
        msg: |
          OrangePi Full Configuration Completed!
          - Platform optimized for embedded hardware
          - OPI-Setup FastAPI service deployed and running
          - GPIO and hardware access configured
          - Performance optimizations applied
          - Integration with existing opi-setup project: ACTIVE
          - Phase 5.2 OrangePi Platform Support: COMPLETE ✅
