---
# Playbook to apply server optimizations to macOS devices
- name: Apply server-like optimizations to macOS
  hosts: all
  gather_facts: false
  tags: ["server"]
  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Verify target is macOS
      ansible.builtin.fail:
        msg: "This playbook only supports macOS"
      when: ansible_distribution != "MacOSX"

  roles:
    - role: macos/server_optimizations
      tags: ["server", "configuration", "optimization"]

  post_tasks:
    - name: Display completion message
      ansible.builtin.debug:
        msg: |
          Server optimizations applied successfully!
          For maximum effect, please restart the system.
      tags: ["always"]
