---
# Default variables for macos_api role

# API configuration
macos_api_port: 9090
macos_api_host: "0.0.0.0"

# Installation paths
macos_api_install_dir: "{{ ansible_user_dir }}/orangead/macos-api"
macos_api_logs_dir: "{{ ansible_user_dir }}/orangead/macos-api/logs"
macos_api_venv_dir: "{{ ansible_user_dir }}/orangead/macos-api/.venv"

# Service user
macos_api_user: "{{ ansible_user }}"
macos_api_group: staff

# Python configuration
macos_python:
  version: "{{ runtime.python.version | default('3.11.11') }}"
