---
# Default variables for macos_api role

# API configuration
api_port: 9090
api_host: "0.0.0.0"

# Installation paths
api_install_dir: "{{ ansible_user_dir }}/orangead/macos-api"
api_logs_dir: "{{ ansible_user_dir }}/orangead/macos-api/logs"
api_venv_dir: "{{ ansible_user_dir }}/orangead/macos-api/.venv"

# Service user
api_user: "{{ ansible_user }}"
api_group: staff
