---
# Install and configure pyenv and Python
- name: Configure pyenv and Python
  block:
    # Check if pyenv is already installed
    - name: Check if pyenv is installed
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.pyenv"
      register: pyenv_install

    # Install pyenv if not already installed
    - name: Install pyenv
      ansible.builtin.git:
        repo: https://github.com/pyenv/pyenv.git
        dest: "{{ ansible_env.HOME }}/.pyenv"
        version: master
        update: yes
      when: not pyenv_install.stat.exists

    # Add pyenv to PATH
    - name: Add pyenv to PATH
      ansible.builtin.lineinfile:
        dest: "{{ ansible_env.HOME }}/.bash_profile"
        line: 'export PATH="$HOME/.pyenv/bin:$PATH"'
        create: yes

    # Initialize pyenv
    - name: Initialize pyenv
      ansible.builtin.lineinfile:
        dest: "{{ ansible_env.HOME }}/.bash_profile"
        line: 'eval "$(pyenv init -)"'
        create: yes

    # Check if Python version is installed
    - name: Check if Python version is installed
      shell: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$($PYENV_ROOT/bin/pyenv init -)"
        $PYENV_ROOT/bin/pyenv versions --bare
      register: installed_versions
      changed_when: false

    # Install Python version
    - name: Install Python version
      shell: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$($PYENV_ROOT/bin/pyenv init -)"
        $PYENV_ROOT/bin/pyenv install {{ python.version }}
      when: python.version not in (installed_versions.stdout_lines | default([]))

    # Set global Python version
    - name: Set global Python version
      shell: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$($PYENV_ROOT/bin/pyenv init -)"
        $PYENV_ROOT/bin/pyenv global {{ python.version }}
      register: pyenv_set_global
      changed_when: pyenv_set_global.rc == 0

    # Rehash pyenv only when new version is installed
    - name: Rehash pyenv
      ansible.builtin.shell: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        pyenv rehash
      args:
        executable: /bin/bash
      when: pyenv_set_global.changed | default(false)

  when: configure.pyenv | bool
  # This entire block will only run if configure.pyenv is set to true in default.config.yml
