---
# Ubuntu ML Workstation Setup
# Modular task orchestration for improved maintainability and idempotency

# System validation and information display
- name: System validation and information
  ansible.builtin.include_tasks: system_validation.yml
  tags: ["ml", "info", "validation"]

# Package installation for ML workloads
- name: Package installation
  ansible.builtin.include_tasks: package_installation.yml
  tags: ["ml", "packages", "setup"]

# System optimizations for ML training
- name: System optimization
  ansible.builtin.include_tasks: system_optimization.yml
  tags: ["ml", "optimization", "setup"]

# GPU detection and configuration
- name: GPU detection and setup
  ansible.builtin.include_tasks: gpu_detection.yml
  tags: ["ml", "gpu", "nvidia"]

# Modern NVIDIA installation (activated by -t nvidia or install_nvidia variable)
- name: Modern NVIDIA installation (Driver 570-server + CUDA 12.8)
  ansible.builtin.include_tasks: nvidia_setup_modern.yml
  when: >
    install_nvidia | default(false) or
    'nvidia' in (ansible_run_tags | default([]))
  tags: ["nvidia", "gpu", "cuda"]

# ML environment and data setup
- name: ML environment setup
  ansible.builtin.include_tasks: ml_environment.yml
  tags: ["ml", "environment", "data"]

# Performance and monitoring setup
- name: Performance and monitoring setup
  ansible.builtin.include_tasks: performance_setup.yml
  tags: ["ml", "performance", "monitoring"]
