---
# Ubuntu ML Workstation Setup
# Modular task orchestration for improved maintainability and idempotency

# System validation and information display
- name: System validation and information
  ansible.builtin.include_tasks: system_validation.yml
  tags: ["ml", "info", "validation"]

# Package installation for ML workloads
- name: Package installation
  ansible.builtin.include_tasks: package_installation.yml
  tags: ["ml", "packages", "setup"]

# System optimizations for ML training
- name: System optimization
  ansible.builtin.include_tasks: system_optimization.yml
  tags: ["ml", "optimization", "setup"]

# GPU detection and configuration
- name: GPU detection and setup
  ansible.builtin.include_tasks: gpu_detection.yml
  tags: ["ml", "gpu", "nvidia"]

# ML environment and data setup
- name: ML environment setup
  ansible.builtin.include_tasks: ml_environment.yml
  tags: ["ml", "environment", "data"]

# Performance and monitoring setup
- name: Performance and monitoring setup
  ansible.builtin.include_tasks: performance_setup.yml
  tags: ["ml", "performance", "monitoring"]
